### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.py#10]
We have talked about writing tests, so I thought we should open up an issue to organize this effort.  Below is a todo list of modules that are currently (as of 7/9/14)  being imported into the main __init__.py file for the package. My thoughts for this issue are to organize test writing efforts so that we can track which tests have been written, which are being worked on right now, and who is working on them. This way we can write all the tests, but not duplicate work (duplicating work is already unpleasant, but when it is duplication of writing tests, the pain is magnified :rage:)

- [x] asset_pricing
- [x] career
- [x] compute_fp
- [x] discrete_rv
- [x] ecdf
- [x] estspec
- [x] ifp
- [x] jv
- [x] kalman
- [x] lae
- [x] linproc
- [x] lqcontrol
- [x] lss
- [x] lucastree
- [x] mc_tools [Matt]
- [x] odu
- [x] optgrowth
- [x] quadsums
- [x] rank_nullspace
- [x] riccati
- [x] robustlq
- [x] tauchen
- [x] quant-econ/examples/ [Matt]

I suggest that as someone starts working on tests for a particular module that they say so in a comment on this issue so that we don't end up duplicating work.

Any other suggestions for how we should proceed are encouraged.

**Comment by spencerlyon2** [comment]
Ping

**Comment by spencerlyon2** [comment]
@mmcky  is this ready to close?

**Comment by mmcky** [comment]
Closing as we have some basic test infrastructure in place to run the examples. 
We can improve this later on possibly with: https://github.com/paulgb/runipy
