### ISSUE TITLE
Incorrect instructions for dev environment on QuantEcon wiki?

### ISSUE THREAD

**Issue by davidrpugh** [QuantEcon/QuantEcon.py#126]
All,

I think step 5 in the instructions for setting up the development environment on the QuantEcon Wiki might be wrong.  See this [SO post](http://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install) for a nice discussion of the difference between
```
$ python setup.py install 
```
and 
```
$ python setup.py develop
```
although the difference is somewhat self-evident.

For reference I was taught by the IPython devs that the optimal command is actually
```
$ pip install -e .
```

This may or may not be related to #123 .

**Comment by mmcky** [comment]
I have updated the instructions to inform users this is an option. For my workflow I usually run python at the root level of the package which automatically defaults to running the latest anyway but the develop option is a nice system wide approach.

**Comment by mmcky** [comment]
A PR has been submitted to address this issue on the ``QuantEcon.site`` repo. Closing.
