### ISSUE TITLE
display  methods

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.py#13]
Right now none of our classes print helpful messages when queried at the repl. Let's remedy this by implementing `__str__`, `__repr__`, and `__unicode__` methods. The easiest thing would probably be to just implement `__unicode__` and have the others just call and return its value:

```python
def __str__(self):
    return unicode(self).encode('utf-8')

def __repr__(self):
    return unicode(self).encode('utf-8')
```

Here is a list of classes we need to update:

- [x] ARMA (arma.py)
- [x] AssetPrices (asset_pricing.py)
- [x] CareerWorkerProblem (career.py)
- [x] DiscreteRV (discrete_rv.py)
- [x] ECDF (ecdf.py)
- [x] ConsumerProblem (ifp.py)
- [ ] JvWorker (jv.py)
- [ ] Kalman (kalman.py)
- [ ] LAE (lae.py)
- [ ] LQ (lqcontrol.py)
- [ ] LSS (lss.py)
- [ ] SearchProblem (odu.py)
- [ ] GrowthModel (optgrowth.py)
- [ ] RBLQ (robustlq.py)

**Comment by spencerlyon2** [comment]
I would like like to revisit this and potentially implement it in the next few days.

I wanted to ping this issue to give people a chance to comment on what they would like to see in these.

I like what @albop presented in the previous comment.

We might try something like this (for starters, this is really just to get a conversation going):

```python
    def __str__(self):
        m = "GrowthModel:\n"
        m += "  - beta (discount factor): %.3f\n" % self.beta
        m += "  - u (utility function): %s\n" % self.u.__str__()
        m += "  - f (production function): %s\n" % self.f.__str__()
        m += "  - grid: np.linspace(1e-6, %.2f, %i)\n" % (self.grid.max(),
                                                          self.grid.size)
        return m

    def __repr__(self):
       m = "GrowthModel(beta=%.3f, grid_max=%.3f, grid_size=%i)"
       return m % (self.beta, self.grid.max(), self.grid.size)
```

which produces the following:

```
In [1]: from quantecon.models import GrowthModel

In [2]: g = GrowthModel()

In [3]: g
Out[3]: GrowthModel(beta=0.950, grid_max=2.000, grid_size=150)

In [4]: print(g)
GrowthModel:
  - beta (discount factor): 0.950
  - u (utility function): <ufunc 'log'>
  - f (production function): <function <lambda> at 0x106b7a410>
  - grid: np.linspace(1e-6, 2.00, 150)
```

These are definitely not the only possibilities, but I just wanted to throw them out there as examples of two having a very descriptive `__str__` method and a `__repr__` method that can be copied and pasted and create a new `GrowthModel` instance. I would love it if the `__repr__` for the classes would produce a string containing the code needed to reproduce the object, but when we have functions as parameters I don't know how this is possible.

We could also add other things like `Model Name (Author, Year):` on the first line to add a standard reference in the `__str__` methods.

Does anyone have any suggestions?

**Comment by jstac** [comment]
This would be great to have done.  I don't have any concrete views on how.  I guess I would be in favor of keeping it fairly simple.  For things like the growth model it might be sensible to print out a link to the relevant page on quant-econ.net --- but I don't want push this idea too hard because I know we want to decouple library and website.  Feel free to ignore.

**Comment by spencerlyon2** [comment]
That's a good idea. I'm in favor of it as I see the modes more as serving more of a pedagogical purpose than as standalone tools. 

What did you think about the sketch outlined above?

**Comment by jstac** [comment]
Looks great.

**Comment by mmcky** [comment]
@spencerlyon2 I think your suggestion is excellent. I have used ``__repr__`` for trade classes to present some basic stats (importers, exporters etc) about the object - and it has been really helpful. 

Is there a way we could use sympy to represent the functions?

**Comment by spencerlyon2** [comment]
I hadn't thought of sympy.

I was thinking about trying to use [`inspect.getsource`](https://docs.python.org/2/library/inspect.html#inspect.getsourcefile), but I am worried about the robustness of it.

**Comment by spencerlyon2** [comment]
Closing in favor of #114
