### ISSUE TITLE
Numba warning --- implement a common warning

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#133]
If we're going to use numba systematically throughout QuantEcon.py then each time we try to import, we should reference a common warning should that import fail.  For example see the warning in lss.py.  The warning should be put in a separate file so other modules can use it.

**Comment by jstac** [comment]
Should we make this a warning that numba is going to become a dependency?

**Comment by spencerlyon2** [comment]
I think the warning should mention that it is currently strongly recommended and will one day be an explicit dependency.

**Comment by albop** [comment]
To me, we should use the fact that the library is in its early days to increase requirements when necessary, i.e. without delays. Most of the people will get the warning when they update quantecon, and at the moment they update, they will be gently prompted to install numba.

I am a little bit more worried about people who have an incorrect version of numba (too high or too low). In corporate environments, it is often "possible" to install things. But keeping them up-to-date is another matter and requires constant fights.

Maybe it would also be good to give some idea of how stable the library is and whether api breaks are to be expected or not. If we say that version 1.0 is to be expected X months from now, then we have some room to make disruptive changes now.

**Comment by jstac** [comment]
Thanks for these thoughts.

In terms of versions of Numba, I guess the best we can do for people is stay behind the curve a little, and not immediately adopt the latest features that come out.

Dependencies: I've thought this over a bit more and my current view is that although Numba is going to play a very important role for us, I'm not sure we need to move it to an explicit dependency in the short or medium term.  My reasons are

1. Having a NumPy based version of routines is a great way to test Numba-fied functions.  

2. The amount of code that actually gets Numba-fied out of a given module will be small.  Hence it's not a big deal to pair it with equivalent vectorized code.

3. In many cases we will already have the NumPy routines already written.  

If people agree with this then let's just adopt a warning telling people their code will run significantly slower without Numba, and revisit the dependency issue down the road.

Good idea about a plan for version 1.0.  I think we should feel free to break APIs in the short term.

**Comment by mmcky** [comment]
Just running through open issues. I have pushed a suggestion in branch ``numba_warning`` and will submit a PR for comment to get this issue closed.
