### ISSUE TITLE
Need a MANIFEST.in file?

### ISSUE THREAD

**Issue by davidrpugh** [QuantEcon/QuantEcon.py#135]
@jstac @mmcky 

It would appear from looking at the MANIFEST file that none of the LICENSE, README, etc files are included in the `quantecon` source distribution. Is this accurate? I have typically added a `MANIFEST.in` file as described in the [python docs](https://docs.python.org/2/distutils/sourcedist.html#manifest-template) to specify additional files to include as part of the source in my other projects. 

My `MANIFEST.in` file usually just has one line....
```
include *.md LICENSE
```
to include any markdown files (i.e., `README.md`) and the license file.

**Comment by mmcky** [comment]
Hey @davidrpugh thanks for pointing this out. Currently the license "BSD" is declared in the ``setup.py`` configuration but you are right the file is not actually distributed with the ``SDIST``. 

Added #136

**Comment by jstac** [comment]
@davidrpugh Thanks for pointing this out.
