### ISSUE TITLE
Python wheels

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#141]
Is this something we should switch to?

http://pythonwheels.com/

**Comment by davidrpugh** [comment]
I have experimented with wheels a bit.  Seems pretty straightforward to build them and they are the [preferred method of install](https://pip.pypa.io/en/latest/user_guide.html#installing-from-wheels) for pip. Don't see any downside.

**Comment by mmcky** [comment]
Something we should probably migrate to at some point - but not urgent. 

https://packaging.python.org/en/latest/wheel_egg.html

I don't imagine it will be too difficult given our package is currently a source distribution.

**Comment by albop** [comment]
As @davidrpugh  says I don't see any downside either. Since it is apparently becoming the standard, it is probably a good idea. It won't make a big difference though as quantecon is essentially a source distribution, and that is a very good thing to me.

**Comment by albop** [comment]
Hmm, I didn't read @mmcy's comment until later. Please discard mine, it is the same.

**Comment by mmcky** [comment]
We have added instructions for generating a wheel distribution for QuantEcon.py and will be uploaded on the next publish to pypi.
