### ISSUE TITLE
Migrate some modules to util subpackage

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#165]
Some files that should be moved to `util`
* common_messages.py
* external.py
* timing.py

**Comment by oyamad** [comment]
`import warnings` in [lss.py](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/lss.py#L12) was forgotten to move to [external.py](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/external.py#L22)?

**Comment by mmcky** [comment]
@oyamad Thanks. Working on a ``update-util`` branch now. I have added to ``external.py``

**Comment by mmcky** [comment]
Closing as any comments can be added to the PR.
