### ISSUE TITLE
Improve build times for Travis by removing sudo commands from .travis.yml

### ISSUE THREAD

**Issue by davidrpugh** [QuantEcon/QuantEcon.py#167]
@jstac @mmcky 

Travis CI has new [container based infrastructure](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) that should substantially speed up build times for CI.  To use it, at least for the moment, we [can't use `sudo` commands](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) in the `.travis.yml` file.

Should we consider re-working the `.travis.yml` file to remove the sudo commands?

**Comment by mmcky** [comment]
@cc7768 Is this straight forward? I see we have two ``sudo`` commands

```bash
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
```

during ``install`` setup.

**Comment by davidrpugh** [comment]
Might be...I am not exactly sure what those lines are doing. I know what the unix commands are doing, but I don't understand why they need to be there.

**Comment by cc7768** [comment]
I picked up most of that file from [this gist](https://gist.github.com/dan-blanchard/7045057). He said it was an issue with multi-processing on Travis. It could have been fixed by now (though I don't know) -- Feel free to experiment and remove those lines.

**Comment by davidrpugh** [comment]
In that case we might as well delete and see what happens...

**Comment by mmcky** [comment]
This has been fixed and Travis now compiles using containers.
