### ISSUE TITLE
readthedocs - missing a few autojit functions

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#170]
@cc7768 @spencerlyon2 Do either of you have an idea of why this utilities page only has one of two functions contained in the module. When I compile docs locally it has both functions - but they do not appear on readthedocs!

Summary of observations
----------------------------------
  1. Seem to be related to ``numba`` functions. 
  1. ``random.utilities`` is missing ``sample_without_replacement``
  1. ``lss.py`` is missing a function

Generated ``rst`` files look to be correct. Might be a ``readthedocs`` environment issue.

**Comment by spencerlyon2** [comment]
I'm sorry I don't know what is wrong here... Strange that you get it to work locally but rtd fails

**Comment by oyamad** [comment]
There were issues on this, such as numba/numba#134 and numba/numba#470, but it seems to have been fixed by numba/numba#508. I don't see why it is not working for us...

**Comment by mmcky** [comment]
**Update:** As far as I can tell - this might be an issue due to the use of a Mock ``numba`` module perhaps. Maybe it's preventing proper parsing of the docstrings attached to jitted functions. Replacing the ``rtd-pip-requirements.txt`` file with a conda enironment hasn't solved the issue. Will look into this further as it will become a big issue for us.

**Comment by mmcky** [comment]
We have now removed mock from ``rtd`` compilation and making use of the ``conda`` environment with a ``rtd`` yaml config file and coda environment definitions. **Note:** the ``rtd`` support for conda is currently in ``beta`` so we should keep an eye on the documentation site for compilation issues.
