### ISSUE TITLE
[Dependancy] Propose introduction of dependancy on Numba

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#173]
Given ``numba`` is maturing quickly and hasn't presented any major issues thus far when using the library. Is it the right time to introduce  ``numba`` as a strict dependancy of the package?

  1. Allows for the tailored use of ``numba`` when writing new code for the library.
  1. Reduce the need to maintain multiple versions and use of replacement ``jit`` functions. Older ``numpy`` or pure ``python`` versions could be moved to another ``repo`` or a ``teaching`` subpackage for future reference or for the purposes of teaching. 
  1. Everyone I know is using ``anaconda`` which comes with ``numba`` automatically. 

Technically it is also already in ``pip-requirements.txt``.

**Comment by spencerlyon2** [comment]
I'm totally in favor of a strict numba dependency. +1 from me

**Comment by cc7768** [comment]
I am also in favor of this.

**Comment by oyamad** [comment]
I am strongly in favor of this.

**Comment by davidrpugh** [comment]
Agreed.

**Comment by jstac** [comment]
I'm in favor too.  As @mmcky says, numba has proved stable, and any dependency hassle for users is more than offset by a higher performance library, which will in turn benefit users and developers.

@albop are you happy for us to go ahead with this?

I don't believe there's a need for a `teaching` subpackage.  Teaching related material can go in the examples dir of the repo or in a separate repo.

**Comment by mmcky** [comment]
I think this issue can be closed. All seem to be in favour of listing ``numba`` as a dependancy.  The use of the ``anaconda`` distribution means ``numba`` comes packaged.

**Comment by moldovean** [comment]
import quantecon as qe no longer works and I can't install numba

**Comment by mmcky** [comment]
@moldovean Are you using the latest ``anaconda`` with Python ``3.5``? 

If you are the current ``anaconda`` release doesn't come with numba packaged for python ``3.5``. It is available using ``conda install numba`` - and hopefully ``anaconda`` will be updated shortly.
