### ISSUE TITLE
Broken examples python files

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#179]
The following example files need to be fixed

  1. ``lakemodel_example.py`` - attribute and class issues
  1. ``paths_and_hist.py`` - range issues when generating histogram
  1. ``robust_monopolist.py`` - convergence issues

**Comment by mmcky** [comment]
The following examples have been fixed

 ``lakemodel_example.py``
``paths_and_hist.py``

**Comment by finmod** [comment]
Fine. lakemodel_example and paths_and_hist.py are now working correctly in Python 3.4, conda 3.17.0 and quantecon 0.2.0. However, there is the same [sigma] [0] correction to implement in paths_and_stationary.py for completeness.

**Comment by finmod** [comment]
For lakemodel_solutions.py the migration to matplotlib 1.4.3 in python 3.4 should also be implemented. Basically, include "plt." in front of all the matplotlib commands.

**Comment by mmcky** [comment]
@finmod Thanks for your comments. 
I am not sure I understand your comment regarding ``paths_and_stationary.py``. There was a commit that changed the C vector from a row vector to a column vector for that file. Current master has:

```python
C = [[sigma], [0], [0], [0]]
```

**Comment by finmod** [comment]
Current master is correct then. Thank you.

**Comment by jstac** [comment]
@finmod Thanks for your comments.  We'll fix the lake model solutions.

**Comment by finmod** [comment]
You are welcome. Congratulations to you and the Quantecon team for producing this site. It is the best and friendliest introduction to Python I could find on line. The “Setting up your Python environment” is simply outstanding, particularly for Windows OS. All the minor mistakes/updates on “how to” are corrected quickly. You may review your advice about Python 2.7 for novices in the light of the recent migration of scipy, matplotlib, cythonmagic and quite a few others to Python 3.4 as standard.

**Comment by jstac** [comment]
@finmod Thanks, yep, it's on our radar.  Should be done before too long.

**Comment by JohnLeary** [comment]
I have been following this thread to try and learn so would like to visit the site you are referring to. There several quantecon web pages.

**Comment by finmod** [comment]
The Quantecon website and python doc there:  <http://quant-econ.net/py/index.html> http://quant-econ.net/py/index.html

**Comment by mmcky** [comment]
Closing this general issue. Most of these have been addressed and new test scripts for the examples collection have been written and therefore can be tracked when compiling the project. This links to https://github.com/QuantEcon/QuantEcon.py/issues/178
