### ISSUE TITLE
interp in NumPy/SciPy

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.py#189]
This is a minor issue.
In the whole library, `interp` is imported as from `scipy`, and [one of the lectures states](http://quant-econ.net/py/dp_intro.html#comments-on-the-code) "Linear interpolation is performed by SciPy’s `interp` function", but it is actually a function from NumPy ([numpy.interp](http://docs.scipy.org/doc/numpy/reference/generated/numpy.interp.html)).

Importing from `scipy` is fine because the [`__init__.py`](https://github.com/scipy/scipy/blob/master/scipy/__init__.py#L69) in SciPy has `from numpy import *`. The problem is that if the user looks into SciPy for the documentation (as I did), it is not found there, but in NumPy.

**Comment by mmcky** [comment]
Thanks @oyamad - you are correct - this should be fixed. The alternative would be to use `interp1d` which is imported from scipy.

**Comment by lbui01** [comment]
Hi @oyamad  - I have opened a PR to change the scipy.interp to be directly used from numpy. See PR jstac/QuantEcon.lectures#90

This also needs to be updated in the solutions_py.ipynb. See issue jstac/QuantEcon.lectures#92.

We should be able to close this issue soon.

Also note:

I ran a speed test for np.interp and scipy.interpolate.interp1d and found that np.interp was significantly faster. 8.31ms for interp and 38.4ms for interp1d (including initializing the function). If anyone is interested, see this gist: https://gist.github.com/lbui01/1e7f2bffeae8296a31e49727bb710ef4

**Comment by jstac** [comment]
@lbui01 Thanks, nice work.  

I guess the main difference is that `interp` returns an array whereas `interp1d` returns a callable object.

Having a callable object (e.g., a function) is often more convenient.  In fact you can see in this line

```
w_func = lambda x: interp(x, grid, w)
```

from the [optimal growth lecture](https://lectures.quantecon.org/py/optgrowth.html) that I'm creating a callable using `lambda` syntax.  If I'd known I might have just used `interp1d1`.

I looked at the relative performance as well, and, if you do want to make a callable, then `interp` is only slightly faster.  See [here](https://gist.github.com/anonymous/c8655f020383ad48ba427d9f8cc28ff4).  That kind of difference is negligible.

**Comment by jstac** [comment]
In summary, if we want to make a callable I suggest we use `interp1d` imported from SciPy, whereas if we only wish to make an array (i.e., evaluate once off) then we use `interp`, imported from NumPy.

**Comment by lbui01** [comment]
Thanks @jstac, I see why ``interp1d`` is useful.
