### ISSUE TITLE
Arellano_solutions migration to matplotlib 1.4.3 in python 3.4

### ISSUE THREAD

**Issue by finmod** [QuantEcon/QuantEcon.py#190]
The following error appears in arellano_solutions in the plotting the last three time series.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Users\Denis\Anaconda3\lib\site-packages\quantecon\markov\core.py in simulate(self, ts_length, init, num_reps, random_state)
    351         try:
--> 352             k = len(init)  # init is an array
    353             dim = 2

TypeError: object of type 'numpy.int64' has no len()

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-7-45523b0b0cfd> in <module>()
      1 T = 250
----> 2 y_vec, B_vec, q_vec, default_vec = ae.simulate(T)
      3 
      4 # Pick up default start and end dates
      5 start_end_pairs = []

C:\Users\Denis\Anaconda3\lib\site-packages\quantecon\models\arellano_vfi.py in simulate(self, T, y_init, B_init)
    164         mc = qe.markov.MarkovChain(self.Py)
    165 
--> 166         y_sim_indices = mc.simulate(T, init=y_init)
    167         B_sim_indices = np.empty(T, dtype=np.int64)
    168         B_sim_indices[0] = B_init

C:\Users\Denis\Anaconda3\lib\site-packages\quantecon\markov\core.py in simulate(self, ts_length, init, num_reps, random_state)
    367             else:
    368                 raise ValueError(
--> 369                     'init must be int, array_like of ints, or None'
    370                 )
    371 

ValueError: init must be int, array_like of ints, or None

**Comment by oyamad** [comment]
@finmod Thank you for the report. This seems to be a bug in `MarkovChain`.

[This line](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/markov/core.py#L365) should have been `elif isinstance(init, (numbers.Integral, np.integer)):` as in [here](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/util/random.py#L27), since "numpy.int64 is not instance of int" (numpy/numpy#2951) (I didn't know this).

To double check, I have to set up a Python 3 environment, and I will then fix this tomorrow.

**Comment by oyamad** [comment]
Maybe `elif isinstance(init, numbers.Integral):` is enough (numpy/numpy#4547).

**Comment by finmod** [comment]
None of the two patches.

 

TypeError                                 Traceback (most recent call last)

C:\Users\Denis\Anaconda3\lib\site-packages\quantecon\markov\core.py in simulate(self, ts_length, init, num_reps, random_state)

    351         try:

--> 352             k = len(init)  # init is an array

    353             dim = 2

 

TypeError: object of type 'numpy.int64' has no len()

 

During handling of the above exception, another exception occurred:

 

NameError                                 Traceback (most recent call last)

<ipython-input-7-d4165fac13d6> in <module>()

      1 T = 250

----> 2 y_vec, B_vec, q_vec, default_vec = ae.simulate(T)

      3 

      4 # Pick up default start and end dates

      5 start_end_pairs = []

 

C:\Users\Denis\Anaconda3\lib\site-packages\quantecon\models\arellano_vfi.py in simulate(self, T, y_init, B_init)

    164         mc = qe.markov.MarkovChain(self.Py)

    165 

--> 166         y_sim_indices = mc.simulate(T, init=y_init)

    167         B_sim_indices = np.empty(T, dtype=np.int64)

    168         B_sim_indices[0] = B_init

 

C:\Users\Denis\Anaconda3\lib\site-packages\quantecon\markov\core.py in simulate(self, ts_length, init, num_reps, random_state)

    363             if init is None:

    364                 init_states = random_state.randint(self.n, size=k)

--> 365             elif isinstance(init, numbers.Integral):

    366                 init_states = np.ones(k, dtype=int) * init

    367             else:

 

NameError: name 'numbers' is not defined

**Comment by oyamad** [comment]
Thanks @finmod, the `numbers` module has to be imported by `import numbers`.

**Comment by finmod** [comment]
Ok. Spot on by inserting import numbers in core.py and also in the arellano notebook. Thanks

 

Denis Richard
*
***********************************************************
*
* Via Panama, 88
* Rome 00198, Italy
* Tel: +39 06 83 90 66 29
* Cel: +39 32 79 76 12 96
* Email: denis.richard@dr.com
*
***********************************************************
