### ISSUE TITLE
Python 3.4 Review and Default ...

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#192]
Review ``quant-econ.net`` and ``quantecon.org`` for python 3.4 compatibility. 

It is getting close to move to ``python 3.4`` as a default. I don't think we are quite there yet though (i.e. ``fabric`` is not yet ``python3`` compatible - but it looks like it is getting close). Many of our other dependancies have moved up to ``python3.4`` including ``statsmodels``. 

Also - ``Continuum`` default installer is currently ``python2.7`` so for new users it is probably still the best option.

**Comment by mmcky** [comment]
I have just noticed that the ``Anaconda`` download page has been updated. Both ``py27`` and ``py34`` are now promoted side by side. The switch to python 3.4 is pretty close. 

https://www.continuum.io/downloads

**Comment by jstac** [comment]
Hooray. 

What are the issues to discuss here?  `fabric` is only used for compiling the website, which is kind of orthogonal to this library...

**Comment by spencerlyon2** [comment]
@mmcky I don't see what changed? Instead of having the 3.4 link in a separate "tab" (within the page) it is now side by side?

**Comment by davidrpugh** [comment]
@mmcky  

Just to make sure I understand.  We are considering moving to python3.4 and no longer support python2.7?

**Comment by mmcky** [comment]
@davidrpugh et al. I think we should still support both for the immediate future (as we currently do) given it isn't that difficult. However as time roles on - we shouldn't be shy to use ``Python 3`` as a baseline if dependancies start supporting new features in Python 3 only etc. 

We currently recommend ``Python 2.7`` in the lecture series - as that was the "default" anaconda option for downloading from ``continuum``. I was mainly commenting above that ``anaconda`` seems to be moving towards more equal citizens for both versions - making ``Python 3.4`` more directly visible. 

Making ``Python 3.4`` the default probably impacts ``quant-econ.net`` more to make sure the code snippets follow correct ``print`` syntax etc. 

For the package - It will however become important for things like: PEP 465 http://legacy.python.org/dev/peps/pep-0465/#abstract. It is listed for inclusion in Python 3.5 but not sure if it will be back ported to Python 2.7.#.

**Comment by mmcky** [comment]
With the recent release of python ``3.5`` the use of ``@`` for matrix multiplication will be used a lot in new code. We need to update our Travis-CI environment and move towards ``3.5`` as a default.

**Comment by davidrpugh** [comment]
Agreed. +1

**Comment by mmcky** [comment]
The migration to ``python 3.5`` has now occurred. 
The current package supports Python 2.7 but as code get's added using python3.5 syntax we will only support ``python 3.5``. Travis CI has been updated to check the package in a python 3.5 environment.
