### ISSUE TITLE
Test needed for `kalman`

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#200]
`stationary_coefficients` needs a test.  See this discussion:

https://github.com/QuantEcon/QuantEcon.py/pull/199

**Comment by mmcky** [comment]
@lbui01 this isn't urgent -- but with your skills at writing tests. Do you think you might be able to take a look at this one?

**Comment by lbui01** [comment]
@mmcky - yes, happy to do it.

**Comment by mmcky** [comment]
@lbui01 can this be closed now?

**Comment by mmcky** [comment]
Closing as duplicate of #128
