### ISSUE TITLE
Aiyagari examples

### ISSUE THREAD

**Issue by finmod** [QuantEcon/QuantEcon.py#203]
The Aiyagari examples introduced a few days ago require updates of numba and llvm in python 3.4 and anaconda 2.4 to run properly.

**Comment by mmcky** [comment]
Hi @finmod I just tested these in the latest ``anaconda`` environment with ``python=3.5`` and ``anaconda2.5`` which appear to work. Can you let me know if this is still causing you any issues? Thanks.

**Comment by finmod** [comment]
Hello mmcky,

 

Fine, no longer a problem. The only remaining issue is PEP 465: the use of @ for matrix multiplication in place of “dot”. It runs fine on python 3.5 and anaconda 2.5. (Wald Friedman notebook)

 

Instead, it still throws an error in python 2.7. I thought we debated that it should stay as @ everywhere but a trap or warning should be inserted for python 2.7 users saying that A@B should be replaced by dot(A,B) whenever appropriate.

 

Thanks.

**Comment by mmcky** [comment]
I am personally in favour of just supporting python 3.5 given how easy it is to create a compliant environment using ``conda`` and the current state of the python scientific stack in its migration to python3+. My reason for this thinking is that the ``@`` symbol isn't the only change and that some other things like ``itertools`` works differently in python ``3.5`` so if we track ``@`` then we should also track other language differences too.

**Comment by mmcky** [comment]
I will leave this issue open for any further discussion on this.

**Comment by jstac** [comment]
Yes, let's just mention it on the library landing page of QuantEcon.py. @mmcky Would you mind to make a suitable edit on this page:

http://quantecon.org/python_index.html

Just a couple of words at the end of the sentence where we mention Anaconda in the 'Installation' section should be fine.

**Comment by mmcky** [comment]
This can now be closed due to the submitted PR to address this.
