### ISSUE TITLE
Relocate models subpackage 

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#205]
Relocate the ``models`` subpackage to ``examples`` as a more natural fit within the repository. This will provide focus of the main package to reusable algorithms and routines. 

Given the dependencies of some ``example`` files on the code contained in ``models`` this directory will be reorganised into ``topics`` containing related library code and example files.

Example
-----------
1. ``lakemodel_example.py`` imports ``LakeModel, LakeModelAgent, LakeModel_Equilibrium`` from ``quantecon.models``.  Therefore ``models/lake.py`` will be moved into a folder ``examples/LakeModel`` along with ``lakemodel_example.py`` and the import statement will be update to ``from lake import LakeModel, LakeModelAgent, LakeModel_Equilibrium``

**Comment by mmcky** [comment]
This work is now being transferred to a separate quant-econ teaching repository rather than the package examples folder that can be organised in support of lectures and can be used as a teaching package.

**Comment by davidrpugh** [comment]
@mmcky 

This is an excellent idea.  I like the idea of a teaching package.  In particular, I would like to contribute several example notebooks from my [pyCollocation package](https://github.com/davidrpugh/pyCollocation) (once they are sufficiently polished).

**Comment by jstac** [comment]
Shall we have directory names match the file names of the corresponding lectures, where convenient?  For example, code associated with `lake_model.html` would be put in `examples/lake_model`.

**Comment by jstac** [comment]
Perhaps we should add a `notebooks` directory as well as an `examples` directory?  Right now the notebooks on [this page](http://quantecon.org/notebooks/) are stored in QuantEcon.site.  Having them in the site repo seems a bit odd --- it should really be just code for building the site --- and might be a barrier to finding and using those notebooks.  If we make the switch, @davidrpugh would have a natural place to put the collocation notebooks.

**Comment by jstac** [comment]
@mmcky OK to close?

**Comment by mmcky** [comment]
@jstac I think so - I am just reviewing this issue to make sure we can close.
