### ISSUE TITLE
Convert Gambit bindings to Python 3, make conda package

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#218]
Gambit is a useful piece of software for computing Nash equilibria in games, among other things.  

http://www.gambit-project.org/gambit14/index.html#

The core routines are written in C.  There are Python bindings but they are in Python 2 and the developer has no plans to convert to Python 3.  If someone is interested it would valuable to convert to Python 3 and build a conda package.  A start would be to run the bindings through the 2to3 conversion tool and see how much manual work is left. If not much I think this is worth doing.

**Comment by oyamad** [comment]
I have some code on game theory (mostly for simulation of learning/evolutionary dynamics models, and not about computation of Nash equilibria) to submit to QE.py (the base code is ready, while applications are not yet): https://github.com/oyamad/game_theory_models

(I also have a preliminary version in Julia.)

There I have a certain data structure to represent a game, and would be interested in building a wrapper/binding in Python (and Julia) that converts my data structure and passes it to Gambit to return Nash equilibria of the game.

(Just to remind ourselves, Gambit is GPL licensed.)

**Comment by jstac** [comment]
The game theory code looks very promising.

I didn't notice the GPL license.  They might be willing to change the license if we are prepared to update the Python bindings to Python 3 and build a conda package.  I know Andy McLennan well and he is very reasonable.

**Comment by spencerlyon2** [comment]
The GPL wouldn't be an issue for us in quantecon though. 

The wrapper would probably need to be gpl, but we would be able to call it from a BSD qe.py

**Comment by oyamad** [comment]
I opened a PR #220, just for the base classes this time.

**Comment by oyamad** [comment]
This has been done by Gambit itself.
