### ISSUE TITLE
filterwarnings

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.py#229]
It seems that once `quantecon` is imported, the warnings the user issues by `warnings.warn` are ignored, probably because of `warnings.filterwarnings('ignore')` in [arma.py](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/arma.py#L16) (and there is also `warnings.simplefilter("ignore", RuntimeWarning)` in [matrix_eqn.py](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/matrix_eqn.py#L22)).

If it is indeed the case, this is problematic. Is there any way to put `warnings.simplefilter` in a "local scope"?

**Comment by oyamad** [comment]
```python
>>> import warnings
>>> warnings.warn('warning')
__main__:1: UserWarning: warning
>>> import quantecon
>>> warnings.warn('warning')
>>>
```

**Comment by spencerlyon2** [comment]
We should definitely not be silencing all warnings. I haven't looked, but do we know why we are even expecting to have warnings in arma.py?

**Comment by mmcky** [comment]
I propose we remove the ``warnings.filterwarnings('ignore')`` and then deal with any warnings that arise.

**Comment by mmcky** [comment]
Comment in ``matrix_eqn.py``

```python
# == Suppress warnings from checking conditioning of matrices == #
```

**Comment by mmcky** [comment]
I propose we remove the ``warnings.filterwarnings('ignore')`` and then deal with any warnings that arise.

**Comment by mmcky** [comment]
Closing this issue as discussion has moved to PR #231
