### ISSUE TITLE
Improved Change Log

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#243]
`pandas` and `numba` have excellent documentation around package changes. It would be nice to incorporate a more formal change log for `quantecon`

**Comment by mmcky** [comment]
@spencerlyon2 Do you happen to know how some of the open source projects track their changes. Is it mainly a love of manual labour or have you seen some nice tools to automatically compile the changes for releases etc?

**Comment by mmcky** [comment]
Given the volume of changes we work with at the moment. I don't see a reason to invest much in a change log tool other than listing the merged PR's. I think I will close this.

**Comment by sglyon** [comment]
Ha, sorry for being almost a year late to the conversation, but no I don't know of any good automated tools for doing this.

**Comment by mmcky** [comment]
no problem. Thanks @sglyon.
