### ISSUE TITLE
Release new PyPI version and update the change log

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#249]
I will put together a new PyPI version release tomorrow. 

I will work my way through the commits from the last pypi version release to update the change log. But if anyone has anything they would specifically like to highlight or an example that demonstrates an interface change to an object etc. Please feel free to add those details and/or code example in this thread. Thanks.

**Comment by cc7768** [comment]
May want to go ahead and do a conda package while we're at it. If you want to create a new issue and "assign" me then I could take care of it this weekend.

http://conda.pydata.org/docs/build_tutorials/pkgs.html

**Comment by spencerlyon2** [comment]
I've heard good things about [conda-forge](https://conda-forge.github.io)

May want to look into that for building the conda package across the 3 main OSs

**Comment by mmcky** [comment]
Thanks @spencerlyon2 and @cc7768 I will take a look at those links.

**Comment by mmcky** [comment]
@cc7768 I will be looking at this first thing on Monday morning. If you have time on Monday - do you want to meet up to go through the ``conda`` package?

**Comment by cc7768** [comment]
Yes. Sounds like a plan. I'll come to that side of the street on Monday morning.

**Comment by mmcky** [comment]
A conda build recipe has been put together and is contained in the ``QuantEcon.py-conda`` repo. Will prepare a new ``pip`` release now.
