### ISSUE TITLE
qe.distributions -- A Python version of Julia's Distributions.jl package

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#257]
We all know that the interface to distributions in scipy.stats is horrible.  It would be great to have a subpackage with distributions that does what Distributions.jl does, with an equally nice interface, and numbafied routines for evaluating pdfs and generating random numbers.

It could be argued that this doesn't belong in quantecon but I don't care.  I still want it.

**Comment by davidrpugh** [comment]
@jstac Agreed. Does it make sense to try for a straight port of the Distributions.jl interfaces?

**Comment by cc7768** [comment]
Relevant: https://www.continuum.io/blog/developer-blog/calling-c-libraries-numba-using-cffi

**Comment by albop** [comment]
+1 That would be very useful.

**Comment by jstac** [comment]
I propose that we deliberately mimic the interface of Distributions.jl with only obvious changes.  Thus,

``` julia
mu, sigma = 0, 1
d = LogNormal(mu, sigma)
rand(d, 4)
```
 becomes

```
mu, sigma = 0, 1
d = LogNormal(mu, sigma)
d.rand(4)
```

The advantage is that we are matching a great interface and we can seamlessly move between them.  

Implementing just 5 or 6 distributions would cover 90% of use cases.  After that we can hope for user contributions.  Code can be taken from scipy.stats or random in the standard library and Numbafied.

**Comment by spencerlyon2** [comment]
Hey team.

I wanted this a few years ago, so I started on a project I called [distcan](https://github.com/spencerlyon2/distcan).

It provides a super simple way to "wrap" distributions from scipy.stats to mimic Distributions.jl

I'd recommend starting here and polishing things up a bit

**Comment by jstac** [comment]
Should have known that @spencerlyon2 would have a project on the go to do this already ;-)

I've asked @danielcsaba to consider working on this project for his course project with me.  @spencerlyon2 Would you be willing to have a chat with him at some stage?

**Comment by spencerlyon2** [comment]
Yep, I think all distcan needs is some developer hours. I got a pretty decent start, but simply ran out of time and ended up using Julia/Distributions.jl more often.

@danielcsaba let me know when/where you want to chat about this

**Comment by danielcsaba** [comment]
thanks @spencerlyon2,  I've just checked out the project you linked

would tomorrow afternoon work for you?

**Comment by spencerlyon2** [comment]
Hey @danielcsaba I'm not in NYC, but can be available via Skype. Send me an email and we can coordinate on times.

**Comment by jstac** [comment]
@spencerlyon2 @danielcsaba Having looked at this a bit more, I would have to say that, as impressive as distcan is, my preference as a consumer would still be to have a small in house subpackage that's numbafied.  Then, on top of the nicer interface, we get routines we can use in numbafied functions.

**Comment by spencerlyon2** [comment]
Sounds good to me. I think a good starting place would be to do [exactly what Distributions.jl did](https://github.com/JuliaLang/Rmath-julia) and write a wrapper around the Rmath C library. You could use the post Chase linked to as a starting point for how to do it (this is exactly the example they talked about in that article).

RMath is GPL, so it would probably be better for us to create this as a standalone package under the quantecon umbrella than to have it within quantecon itself.

**Comment by danielcsaba** [comment]
Sounds good also to me. I will look into the suggested materials and get back soon.

**Comment by jstac** [comment]
Closing since this project has shifted here:

https://github.com/QuantEcon/Distributions.py
