### ISSUE TITLE
Possible Improvements in Continuous Integration

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#258]
Might want to consider upgrading our CI checks to possible include:
1. https://www.codacy.com 
2. https://www.quantifiedcode.com
3. https://www.appveyor.com (CI for Windows distributions)
4. https://codecov.io (Coverage Analytics)

Testing images
1. https://pypi.python.org/pypi/pytest-mpl

**Comment by mmcky** [comment]
May want to consider migrating to pytest: https://docs.pytest.org/en/latest/

**Comment by Smit-create** [comment]
Do we require any more integrations in CI now?

**Comment by mmcky** [comment]
hey @Smit-create I think we are at a good equilibrium point. Thanks for your work in migrating to pytest.

Perhaps the last thing that needs to be done is:

1. remove `tests.yml`
2. rename `conda_ci.yml` to `ci.yml`
