### ISSUE TITLE
No Conda recipe

### ISSUE THREAD

**Issue by arkilic** [QuantEcon/QuantEcon.py#259]
Clearly, this is more of a wish than an issue.

**Comment by mmcky** [comment]
@arkilic We are looking at putting together a conda recipe this week  and will be looking to add it to conda forge.

**Comment by arkilic** [comment]
@mmcky Awesome, thanks!

**Comment by mmcky** [comment]
PR has been submitted for inclusion into ``conda-forge``

https://github.com/conda-forge/staged-recipes/pull/1187

**Comment by arkilic** [comment]
👍

**Comment by mmcky** [comment]
QuantEcon is now installable through conda-forge. Closing this issue.

**Comment by oyamad** [comment]
I didn't know this. Is this documented somewhere?

**Comment by mmcky** [comment]
Hi @oyamad. It isn't specifically documented anywhere yet as we were giving it a "trial" period - to make sure it was running smoothly. When I update the new release of ``0.3.4`` I will document this more widely in the QuantEcon.py repo README and on lectures.quantecon.org
