### ISSUE TITLE
Document Extended Testing Data Requirements

### ISSUE THREAD

**Issue by sanguineturtle** [QuantEcon/QuantEcon.py#27]
This Issue is to collect any Data Requirements we may think when writing tests, that will demand infrastructure for importing a data file etc. 

1. <Module>, <Function>, Brief reason, Brief description of data requirement

**Comment by mmcky** [comment]
@spencerlyon2 Re ``testing_data.h5`` it is version controlled within git. Do we need to write documentation for updating data contained within it? Is that something I need to add to ``quantecon.org/wiki/python``? When you update ``h5`` files do you use python to open, add data and close or do you use a utility like HDFView?

**Comment by spencerlyon2** [comment]
I don't have any docs written for dealing with it.

Whenever I have made updates they have been directly with python -- not any other application. 

Also, I did a quick scan through the repo and can't see the  file you mention. Any idea where it went?

**Comment by mmcky** [comment]
I have it on my local machine. 

It seems to be referenced in

```bash
util.py:    data_file = join(data_dir, "testing_data.h5") 
````

It was deleted August 08, 2014. Does this need to be reinstated?

**Comment by spencerlyon2** [comment]
I don't think so.

i think what we decided was to not have this file checked into git. Then the first time you run the tests it will be created for you so you have a local cache of data (see [here](https://github.com/QuantEcon/QuantEcon.py/blob/557d2fad8f105251d7fb01aacdf6e4c7651d5797/quantecon/tests/util.py#L55-L81)).

**Comment by mmcky** [comment]
@spencerlyon2 Oh I think I understand now. This is really just a container for storing results then rather than persistent data used for testing?

**Comment by spencerlyon2** [comment]
Yep. It just speeds up the running of the tests

If the file is missing, it will be generated when you run the tests.

**Comment by mmcky** [comment]
@spencerlyon2 Great - thanks. Therefore we don't really need documentation to show how to populate the object. I had assumed there were data tables included and hence why I thought it should be version controlled etc. Closing Issue.
