### ISSUE TITLE
Issue new release to PyPI and Conda-Forge

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#274]
Send out a new release with recent additions and fixes

**Comment by cc7768** [comment]
We can go ahead and do this soon since we have a strict dependency on numba 0.28.1 right now, but we should also re-release after 0.30 of numba is released and our problems are fixed.

**Comment by mmcky** [comment]
Thanks @cc7768 for this reminder. Perhaps I will see how long it is expected to be until ``0.30`` release.

**Comment by mmcky** [comment]
Waiting for ``0.30`` release.

**Comment by mmcky** [comment]
Numba ``0.30`` has now been released. However I note that numba is still ``0.28.1`` in the official ``anaconda`` distribution base installer. Should we wait until numba is ``0.30`` in the base installer or are we happy to go ahead given it is in the ``anaconda`` repository using ``conda``?

**Comment by mmcky** [comment]
FYI - still waiting for ``anaconda`` base to upgrade numba to ``0.30`` but monitoring every couple of days.

**Comment by mmcky** [comment]
``anaconda`` has been released to ``4.3.0`` which now includes numba ``0.30.1``. So tomorrow I will release a new version of QuantEcon.py on pip and condo forge.
