### ISSUE TITLE
ValueError: Unsupported target: parallel

### ISSUE THREAD

**Issue by zoof** [QuantEcon/QuantEcon.py#275]
I am getting the above error when I attempt to import `compute_fixed_point`.  I suspect it has something to do with my AMD processor since I have had no problems with Intel processors.  It may also be related to the fact that I am using Python 2.7.  I am running on a Debian Jessie box.  Traceback follows:

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-1-7faf9efa60b9> in <module>()
          5 import matplotlib.pyplot as plt
          6 from numpy import log
    ----> 7 from quantecon import compute_fixed_point

    /home/user/anaconda/lib/python2.7/site-packages/quantecon/__init__.py in <module>()
         12 from . import game_theory
         13 from . import quad
    ---> 14 from . import random
         15 
         16 #-Objects-#

    /home/user/anaconda/lib/python2.7/site-packages/quantecon/random/__init__.py in <module>()
         14 """
         15 
    ---> 16 from .utilities import probvec, sample_without_replacement

    /home/user/anaconda/lib/python2.7/site-packages/quantecon/random/utilities.py in <module>()
         91 _probvec_parallel = guvectorize(
         92     ['(f8[:], f8[:])'], '(n), (k)', nopython=True, target='parallel'
    ---> 93     )(_probvec)
         94 _probvec_cpu = guvectorize(
         95     ['(f8[:], f8[:])'], '(n), (k)', nopython=True, target='cpu'

    /home/user/anaconda/lib/python2.7/site-packages/numba/npyufunc/decorators.pyc in wrap(func)
        161 
        162     def wrap(func):
    --> 163         guvec = GUVectorize(func, signature, **kws)
        164         for fty in ftylist:
        165             guvec.add(fty)

    /home/user/anaconda/lib/python2.7/site-packages/numba/npyufunc/decorators.pyc in __new__(cls, func, signature, **kws)
         40     def __new__(cls, func, signature, **kws):
         41         identity = cls.get_identity(kws)
    ---> 42         imp = cls.get_target_implementation(kws)
         43         return imp(func, signature, identity, kws)
         44 

    /home/user/anaconda/lib/python2.7/site-packages/numba/npyufunc/decorators.pyc in get_target_implementation(cls, kwargs)
         22             return cls.target_registry[target]
         23         except KeyError:
    ---> 24             raise ValueError("Unsupported target: %s" % target)
         25 
         26 

    ValueError: Unsupported target: parallel

**Comment by oyamad** [comment]
@zoof What is the version of `Numba` in your system?

It can be checked by

```py
import numba
print numba.__version__
```

in a Python session, or

```
python -c "import numba; print numba.__version__"
```

at a terminal.

**Comment by zoof** [comment]
Ah, I see the problem.  I upgrade numbapro which downgraded numba to 0.22.1.  Works now, thank you!
