### ISSUE TITLE
Problems with `fetch_nb_dependency`

### ISSUE THREAD

**Issue by cc7768** [QuantEcon/QuantEcon.py#278]
@thomassargent30 was trying to download files from `QuantEcon.applications` and the current dependency fetcher doesn't seem to be able to do this easily.

It might be useful to do the following two things:

* Currently, the function takes a `deps` argument because it helps you get to the dependency folder of `QuantEcon.Notebooks`. In [line 73](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/util/notebooks.py#L73) of the function it joins the `repo`, `raw`, `deps`, and other arguments together. It might make sense to remove the `deps` argument altogether (or rename it to be `folder`) and just require people to use the dictionary approach when getting files from `QuantEcon.Applications`... There could be a few other possible solutions to this, but I think the current design prevents the code from being able to fetch files from other repositories (which I think was one of the goals).
* Write some examples of how this function works.

Both of these seem like relatively easy tasks? Do we have any newer members of the team that might be capable of doing this?

Maybe @mmcky has some design thoughts to fix this?

**Comment by oyamad** [comment]
I agree `deps` will better be `folder`, or `directory`.

A use case is found in Cell `[44]` in [here](http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/ddp_ex_career_py.ipynb#Comparison-with-CareerWorkerProblem).

**Comment by mmcky** [comment]
Only thing left is to: 

- Write some examples of how this function works.

**Comment by mmcky** [comment]
Closing based on PR #279 and #320
