### ISSUE TITLE
TEST: Add tests for arma.py

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#298]
Coverage:

```
arma.py                                123     83    33%
```

needs additional tests. There are a number of plots that will affect coverage. 
Should we test simple executability of these methods -- or add image comparison tests (http://matplotlib.org/devel/testing.html#writing-an-image-comparison-test). I tend to think exectuion is all we are after here and image testing will probably be a headache.

**Comment by jstac** [comment]
Plot functions removed, closing

**Comment by oyamad** [comment]
It seems [some tests are still not covered](https://coveralls.io/builds/13058205/source?filename=quantecon%2Farma.py).
