### ISSUE TITLE
TEST: add tests for cartesian.py

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#299]
Coverage:

```
cartesian.py                            34     13    62%
```

**Comment by oyamad** [comment]
@mmcky What is the status of this issue? We have `cartesian.py` and `gridtools.py`, and `test_gridtools.py` but no `test_cartesian.py`. See also https://github.com/QuantEcon/QuantEcon.py/issues/143#issuecomment-128095418.

**Comment by QBatista** [comment]
@mmcky I'm trying to work on this issue - would you have time to clarify its status?

**Comment by mmcky** [comment]
@oyamad and @QBatista thanks for bringing my attention to this. It looks like ``cartesian.py`` and ``gridtools`` should be merged. They contain the same code (just different docstrings and some formatting changes). Looks like this PR failed to remove it (https://github.com/QuantEcon/QuantEcon.py/pull/149). As we have migrated to using ``grid_tools.py`` I will submit a PR to remove ``cartesian`` and update the appropriate docs page.

**Comment by mmcky** [comment]
This can be closed as `cartesian.py` is now removed.
