### ISSUE TITLE
Pandas routine 'ols' removed. Move to 'statsmodels'

### ISSUE THREAD

**Issue by tlyon3** [QuantEcon/QuantEcon.py#307]
In the 0.20.1 update, pandas remove ols and they recommend dependency on statsmodels. Seems like this error is isolated in the estspec.py file.

**Comment by jstac** [comment]
@tlyon3 Thanks!
@natashawatkins Would you mind to have a look at this?

**Comment by natashawatkins** [comment]
Yep this is also mentioned in PR https://github.com/jstac/QuantEcon.lectures/pull/306

**Comment by natashawatkins** [comment]
Fixed in #308
