### ISSUE TITLE
Fix doc warning

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.py#312]
* [ ] WARNING: Block quote ends without a blank line; unexpected unindent.
  * quantecon/markov/approximation.py

**Comment by oyamad** [comment]
@natashawatkins Has #315 also fixed this?

**Comment by natashawatkins** [comment]
@oyamad Yes! Sorry I wasn't aware of this issue, thanks

**Comment by oyamad** [comment]
Great, thanks!
