### ISSUE TITLE
New features for timing functions

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/QuantEcon.py#322]
`.tic`, `.tac`, `.toc` are relatively basic at the moment.

As discussed in #319, possible improvements include:
* printing results with fewer decimal places by default
* suppressing output
* choosing appropriate units of measurement (similar to `%timeit`)
* running loops (like `%timeit`)

**Comment by albop** [comment]
Another suggestion could be to print the file/line number from where the function is called. This could be done with a bit of metamagic (and a small performance cost).
For running loops, maybe something like https://github.com/QuantEcon/QuantEcon.py/issues/125 could be handy.

**Comment by albop** [comment]
Also, a jitable version of `tic,tac,toc` would be cool. There is a bit of a trade-off between jitteability and functionalities, so maybe there could be two versions.
