### ISSUE TITLE
Remove plotting functionality from ARMA

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#325]
I propose that we remove the plot methods (the last 5 methods) from [the ARMA class](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/arma.py) and embed them in [the lecture](https://lectures.quantecon.org/py/arma.html) instead.

This seems a more natural place for code that produces plots and it also would bring the Python lecture more in line with the Julia lecture --- see the first code block here: https://lectures.quantecon.org/jl/arma.html#code

**Comment by sglyon** [comment]
I think this would also remove the dependency on matplotlib, which would make quantecon even lighter-weight

**Comment by oyamad** [comment]
Now [build is failing](https://travis-ci.org/QuantEcon/QuantEcon.py/jobs/268220128) for some unknown reason, but triggered by `matplotlib` anyway, it is a good timing to remove the dependency on `matplotlib`. Is the task just to remove all the plot function from `arma.py`?

**Comment by jstac** [comment]
I'll work on this now.   The code has to be shifted into the lecture site.

**Comment by oyamad** [comment]
OK, thanks.

**Comment by jstac** [comment]
Umm, so I just accidentally committed to master ;-)

https://github.com/QuantEcon/QuantEcon.py/commit/985d9b8bacf0841ff871540c3f19923ad6465355

But it looks like the build is still failing

**Comment by jstac** [comment]
OK, so I also forgot to remove the import.  I'll do this in a moment.

**Comment by mmcky** [comment]
This looks complete. Closing this issue.
