### ISSUE TITLE
Add OSX to travis.yml configuration

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#359]
Add OS X for platform specific testing in the ``travis.yml`` configuration file. 

```
os:
  - linux
  - osx
```

but the ``before_install`` needs to be made os independent.

https://docs.travis-ci.com/user/multi-os/

**Comment by oyamad** [comment]
Would travis-ci/travis-ci#2312 help? (I didn't read the comments there though.)

**Comment by mmcky** [comment]
thanks @oyamad that just saved me a lot of time. I'm guessing that is probably the reason that ``conda-forge`` uses CircleCI for OSX

https://circleci.com/
