### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.py#36]
As part of the python 3 compatibility push I have been running through all the solutions notebooks. I noticed that the following notebooks took an extra long time to run:

* ifp_solutions
* odu_solutions

This issue is merely a placeholder for us to document where we have noticed opportunities for performance improvements.

**Comment by mmcky** [comment]
@spencerlyon2 Can this issue now be closed? I have on my to do list to get vbench or some performance tracker up and running.

**Comment by spencerlyon2** [comment]
Yep, if it is on your radar we don't need the issue
