### ISSUE TITLE
Include QuantEcon.py in Anaconda

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/QuantEcon.py#370]

**Comment by mmcky** [comment]
This is now happening https://repo.anaconda.com/pkgs/main/

however it looks like the latest version is still `0.5.0` rather than `0.5.2` that is available on `conda-forge`

**Comment by mmcky** [comment]
I have reported this on

https://github.com/ContinuumIO/anaconda-issues/issues/12888
