### ISSUE TITLE
[Style] Use of unicode as arguments and keyword arguments?

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#373]
There has been a proposal to use ``unicode`` arguments for python functions. Give we support python ``3.5+`` this would be technically fine.

However, I would currently vote for **not** using them as I think it might make the library a bit harder to use for some people. But I would like to hear what the community thinks and we can add the decision to a style guide.

**Comment by jstac** [comment]
I also vote not.  In my view this issue can be closed.
