### ISSUE TITLE
remove authors' names

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#394]
I propose we remove authors' names from all files in line with standard open source conventions.

Example: https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/discrete_rv.py

It might be worth flagging this on QuantEcon.jl

**Comment by natashawatkins** [comment]
Should we have a list of contributors somewhere on the webpage or github?

**Comment by jstac** [comment]
GitHub records this info for us anyway.

**Comment by sglyon** [comment]
100% agree!

**Comment by sglyon** [comment]
If they are still on Julia codes we should remove them there also

**Comment by oyamad** [comment]
Fine with me.
