### ISSUE TITLE
Notification: Direct commits!

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#400]
@oyamad and @QBatista Apologies. I made direct commits to the repository this morning to release version ``0.3.8`` without going via a PR. This was my mistake. I will use PR's for future releases to give visibility. 

I will close this in a couple days - just wanted to let you know.

**Comment by oyamad** [comment]
@mmcky No problem. Thanks for letting us know.

I wonder if you could help us in editing `qe_apidoc.py` or other files for PR #392, possibly for version `0.3.8.1` (or `0.3.9`) (so not in a hurry at all).

**Comment by mmcky** [comment]
Hi @oyamad. Absolutely. I have been a bit distracted these past couple of days debugging some of our lecture compilation infrastructure. I can work on getting that documentation working tomorrow (hopefully) - shall I make a setup a PR to your QuantEcon.py fork?

**Comment by oyamad** [comment]
@mmcky Please edit the branch in the fork dicrectly (an invitation sent). Thanks!
