### ISSUE TITLE
Cleanup of QuantEcon.py - November

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#410]
I would like to tidy up QuantEcon.py (thanks @oyamad for kicking this off). Please add any items re: maintenance of the repo below. I will then review this first week of `November`. 

- [x] review ``pip-requirements.txt`` for use and contents (used by `readthedocs` and documented in a new `wiki` page: https://github.com/QuantEcon/QuantEcon.py/wiki/Setup-and-Infrastructure)
- [x] add documentation for generating CHANGELOG.md (this is currently in the `wiki` of this repository). 
- [x] update process to use CHANGELOG.md to document Github release notes (setup this page in the `wiki` https://github.com/QuantEcon/QuantEcon.py/wiki/Releasing-Versions)
- [x] review `.coveragerc`
- [x] review `.coveralls.yml`
- [x] review `.travis.yml`

**Comment by oyamad** [comment]
- [ ] Remove unused data files from `data`

**Comment by oyamad** [comment]
* Test files other than those under `quantecon/tests` are not installed. For example, look into `site-packages/quantecon/markov` on your machine.
* Possibly related to the above and to the role of `pip-requirements.txt`, listing manually subdirectories here https://github.com/QuantEcon/QuantEcon.py/blob/35f41b118b26c12e104d412ff33a252e903c0bfd/setup.py#L97-L104 does not seem really clever. Would `packages=find_packages()` work?

**Comment by mmcky** [comment]
- [x] update year in `LICENSE.txt`
