### ISSUE TITLE
Issue new release of QuantEcon.py

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#425]
I am about to issue a new release of QuantEcon.py and I am thinking of incrementing our major version number to `0.4.0` due to the addition of a new subpackage (`optimize`).  This got me thinking that the way we use version numbers in my head is:

1. ``major version`` = currently `0` to indicate library is in active development
2. ``minor version`` = new subpackage or backward incompatible change (currently `3`)
3. ``minor-minor version`` = new features and bug fixes (currently `9`)

Does everyone agree with this logic? @jstac @oyamad

**Comment by jstac** [comment]
Sounds good to me @mmcky

**Comment by davidrpugh** [comment]
@mmcky your logic seems very similar to the ideas in [semantic versioning](https://semver.org/).

**Comment by mmcky** [comment]
thanks for the link @davidrpugh. Great.
