### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#44]
At this stage we have no discussion of profiling code to find bottlenecks.  Here's the IPython solution:

http://pynash.org/2013/03/06/timing-and-profiling.html

I also hear good things about this visual profiling library:

http://pycallgraph.slowchop.com/en/master/

**Comment by spencerlyon2** [comment]
Ping.

Any interest in writing a suite of performance benchmarks that are tracked via vbench?

**Comment by davidrpugh** [comment]
Possibly, but will need to read up on [vbench](https://github.com/pydata/vbench) first...

**Comment by mmcky** [comment]
Anyone come across any other performance benchmark approaches other than ``vbench``? I notice that the ``bench`` project hasn't had any contributions since 2013 - and pandas benchmarks end in 2012.  Just thought I would check before investing time into this.

**Comment by mmcky** [comment]
I have just come across this project which looks like a good benchmarking tool.
https://github.com/spacetelescope/asv/
It looks like ``pandas`` and ``astropy`` have started to use this. 
Example site: http://mdboom.github.io/astropy-benchmark/

**Comment by jstac** [comment]
@mmcky It definitely looks useful.  You need stable hardware to keep the comparisons consistent but we will have that soon in Singapore...

**Comment by mmcky** [comment]
Setup and try: https://github.com/spacetelescope/asv

**Comment by mmcky** [comment]
I have started setting up ``asv`` benchmarks for ``QuantEcon.py``. 
It currently contains only two benchmarks which is an ``arma`` ``simulation`` and ``impulse response`` but I will use ``tests`` to populate some more benchmarks over the coming weeks. 

https://github.com/QuantEcon/QuantEcon.py.benchmark

**Comment by mmcky** [comment]
I think this issue can now be tracked through the new repository -- except the original comments about profiling are still valid. @jstac should we move your early comments to a ``new lecture`` issue?

**Comment by jstac** [comment]
@mmcky Good call, yes please.

**Comment by mmcky** [comment]
Closing this discussion now. New comments on ``vbench`` and profiling can be made in the [benchmark](https://github.com/QuantEcon/QuantEcon.py.benchmark) repo.
