### ISSUE TITLE
docs won't compile local version

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/QuantEcon.py#460]
I'm getting this error:

![image](https://user-images.githubusercontent.com/21038129/49778096-84fdae80-fd57-11e8-9d7b-0987819679a0.png)

**Comment by rht** [comment]
Strange that the `matplotlib` error happens 1. only recently, 2. only at a specific `:math:` line. Possibly `matplotlib.sphinxext.only_directives` used to be builtin, then it is no longer the case at most recent sphinx version.

**Comment by mmcky** [comment]
@natashawatkins I am not getting this error on my machine.

**Comment by oyamad** [comment]
I have the same problem with `Python 3.7.2` and `Sphinx 2.0.0`.

**Comment by oyamad** [comment]
Any update on this issue??

**Comment by mmcky** [comment]
@oyamad I will be back in the office on Tuesday so will try and replicate this issue using `sphinx=2.0`. I have been using `sphinx=1.7.8` with the latest python with no issues.

**Comment by oyamad** [comment]
No longer relevant?

**Comment by mmcky** [comment]
Confirmed -- I can run the docs build locally. Thanks @oyamad
