### ISSUE TITLE
possibly outdated installation  documentation 

### ISSUE THREAD

**Issue by massich** [QuantEcon/QuantEcon.py#463]
I was googling how to have a dual conda environment (one for users, one for dev) and I ended up here:https://quantecon.org/wiki-py-conda-dev-env I checked up the repo, and you no longer have conda enviroments and have migrated to pip environments.

maybe you want to check it. 

---
ps: shall I forget about conda and migrate everything to pip?  I couldn't find your discussion about it. (https://github.com/QuantEcon/QuantEcon.py/issues/423)

**Comment by mmcky** [comment]
thanks @massich for reporting I will check this.

**Comment by mmcky** [comment]
hi @massich we changed our `read the docs` to use `pip-requirements` mainly to remove some duplication. We still use `anaconda` and `anaconda` environments for development of `quantecon`. We find `anaconda` really good to work with -- but use `pip` for simpler environment tasks such as `rtd` and `travis`

**Comment by mmcky** [comment]
we mainly leave users to define their own environments. But having a conda environment file is an interesting idea for consistency in development work for sure.
