### ISSUE TITLE
Review LGTM Code Quality Suggestions

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#466]
We currently have a very high mark on code quality thanks to testing and linting etc. 

However we should review the code suggestions provided by LGTM

https://lgtm.com/projects/g/QuantEcon/QuantEcon.py/alerts?mode=list

**Comment by nshea3** [comment]
Hi @mmcky! Would be interested in taking on this work. 

I noticed the issue is a little old, is there still an interest in getting this done?

**Comment by mmcky** [comment]
hi @nshea3 that would be great - thanks. I'm keen to see what suggestions it has. But `on other projects` I have grown to like some of the `pre-commit` style looks like `black` etc. for code-reformatting.

**Comment by oyamad** [comment]
@mmcky This has been done and can be closed?

**Comment by mmcky** [comment]
thansk @nshea3 and @oyamad
