### ISSUE TITLE
Error resulting from DiscreteDP?

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/QuantEcon.py#481]
I get the following error in this notebook: https://lectures.quantecon.org/py/discrete_dp.html

![image](https://user-images.githubusercontent.com/21038129/55976225-04cc6300-5ccf-11e9-94c0-8ffc49d9e861.png)

**Comment by natashawatkins** [comment]
Not sure why because the function appears to be correct: https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.linalg.spsolve.html

**Comment by jstac** [comment]
Confirmed.  I get the same error running locally with Anaconda 3.7 and SciPy version 1.1.0.

@oyamad Have you seen this?

CC @QBatista

**Comment by oyamad** [comment]
It seems that this bug realizes as a real bug thanks to e265b2541de8e827b7f20236b6f97ed087216aad.

Compare

```py
>>> import scipy.sparse
>>> scipy.sparse.linalg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scipy.sparse' has no attribute 'linalg'
```

and

```py
>>> import scipy.sparse
>>> import scipy.signal
>>> scipy.sparse.linalg
<module 'scipy.sparse.linalg' from '/Applications/anaconda/lib/python3.7/site-packages/scipy/sparse/linalg/__init__.py'>
```

**Comment by oyamad** [comment]
This should work now with `master`.
