### ISSUE TITLE
Tests of `rouwenhorst` fails occasionally

### ISSUE THREAD

**Issue by shizejin** [QuantEcon/QuantEcon.py#491]
I found test error of `rouwenhorst` in [build log](https://travis-ci.org/QuantEcon/QuantEcon.py/jobs/554096092#L1047) of #489.  There is no build error when I resubmit the exactly same commit for `LQMarkov`, and I guess this error is occasionally triggered by certain random values.

For example, the same error is triggered 7 times during 1000 runs.

<img width="1371" alt="Screen Shot 2019-07-04 at 15 22 26" src="https://user-images.githubusercontent.com/22466278/60647145-9d5a2580-9e6f-11e9-93b9-1a82b0a0393c.png">

**Comment by jstac** [comment]
Thanks @shizejin.  It looks like `tol` should be increased to, say, `1e-10`.  Does that fix it?

**Comment by shizejin** [comment]
@jstac Yes It works, the error only occur 5 times for 100000 runs after I increase `tol` to be `1e-10`.

**Comment by jstac** [comment]
I think that's good enough.
