### ISSUE TITLE
TypingError appearing on Python lectures on stochastic growth

### ISSUE THREAD

**Issue by ssingleton** [QuantEcon/QuantEcon.py#499]
Here is the head of the error on Stochastic Growth 1:
`TypingError                               Traceback (most recent call last)
<ipython-input-10-597809653131> in <module>
      3 
      4 v_init = v_star(grid, α, β, μ)    # Start at the solution
----> 5 v = T(v_init)                     # Apply the Bellman operator once
      6 
      7 fig, ax = plt.subplots(figsize=(9, 5))`

Here is the head of the error on Stochastic Growth 2:
`TypingError                               Traceback (most recent call last)
<ipython-input-9-7c0cb6c2538d> in <module>
      7 for i in range(sim_length):
      8     σ = K(σ)  # Time iteration
----> 9     v = T(v)  # Value function iteration
     10 
     11 # Calculate difference with actual solution`

There are more errors, but I didn't want to overwhelm this page.

**Comment by jstac** [comment]
Thanks @ssingleton, much appreciated!

Numba has changed and broken our jitted scalar optimizer.  See #495.  This is flowing on to our lectures.

@mmcky has put together a temporary fix but I guess it's not published yet?

**Comment by mmcky** [comment]
hey @ssingleton thanks for the report. 

The local fix if you would like to run those lectures is to upgrade `numba` 

``conda install numba=0.44.1``

@jstac the update to `0.44.1` hasn't been pushed yet due to the introduction of the other failure for the `int_` type checking issue.

**Comment by mmcky** [comment]
the latest release of anaconda has `numba=0.45.1` so this should no longer be an issue.

**Comment by mmcky** [comment]
thanks @ssingleton for reporting this. Please let us know if you spot any other errors.
