### ISSUE TITLE
Link to python lectures on GitHub page not working

### ISSUE THREAD

**Issue by duncanhobbs** [QuantEcon/QuantEcon.py#511]
On the QuantEcon.py [Github page](https://github.com/QuantEcon/QuantEcon.py), clicking on the link http://quantecon.org/python_index.html at the top of the page and in `Readme.md` routes to [this page](https://quantecon.org/python_index.html) where it says "Page Not Found".

Is this where the link should send people?

It seems like the link should send people [here](https://python.quantecon.org/) but I am not sure. 

Does it no longer redirect people there? 

@mmcky

**Comment by mmcky** [comment]
thanks for reporting this @duncanhobbs -- I have just updated this on QuantEcon.py.

**Comment by mmcky** [comment]
redirected to https://quantecon.org/quantecon-py/
