### ISSUE TITLE
Update GitHub Actions to check against latest Anaconda Distribution 

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#514]
As we recommend users to use `anaconda` we should update ~~`travis`~~ `github` to use the latest `anaconda` distribution. This will be slower for `CI` but more consistent with user reports of versions (particularly relating to `numba` errors and issues)

**Comment by oyamad** [comment]
@mmcky Travis is no longer used?

**Comment by mmcky** [comment]
Thanks @oyamad indeed we no longer use `travis` 👍 

Our current testing however also just uses `pip` packages so we don't actually tests against the latest anaconda

- [ ] setup another test against latest `anaconda` packages
