### ISSUE TITLE
Update the lower bound for Numba version

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.py#516]
https://github.com/QuantEcon/QuantEcon.py/blob/ad70e0ec715071621e3ffe4c741b4882b0f6c0f4/setup.py#L105

Ref #495

**Comment by mmcky** [comment]
@oyamad do you think this is necessary? Are users using earlier version of `numba<0.38`?

**Comment by oyamad** [comment]
The lower bound should be either updated or removed. (The latter is fine with me.)
