### ISSUE TITLE
Updates to readme pages for QuantEcon.py and QuantEcon.jl

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#517]
There's at least one spelling error in README.md

But more importantly, to reduce the number of pages we need to maintain, I propose that we take the content of [this page](https://quantecon.org/quantecon-py/) and insert it into the README page of the repo.

It might not look as nice but the price is probably worth paying.

More generally, it's not a good idea to have two pages with the same role, and GH readmes are now the established way to describe a library.

Similar comments apply to the Julia side.  CC @sglyon @mmcky @DrDrij

**Comment by mmcky** [comment]
thanks @jstac I agree. I'll merge the suggested page into the README and remove the page in the org repository (https://github.com/QuantEcon/website/blob/master/pages/quantecon-py.md)
