### ISSUE TITLE
Make test-all

### ISSUE THREAD

**Issue by timilak** [QuantEcon/QuantEcon.py#523]
Hi all,

There are two issues with the "make test-all" command. First, nose tests pass but then test-examples fails since there is no scripts/test-examples.py directory (or file) or test-solutions fails since there is no scripts/test-solutions.py (directory or file) in the home directory (under Quantecon.py/ directory). However the individual tests pass when I go to, say for example, quantecon/game_theory/tests/ and run a specific test*.py test. 

Will be helpful if you can guide where the missing scripts/ directory is or how it gets generated.

thanks

**Comment by mmcky** [comment]
thanks @timilak. We should probably remove those `make` commands as they are not actually used for `travis` continuous integration tests. 

We use the following for each PR. 

```
nosetests --with-coverage -a "!slow" --cover-package=quantecon
```

**Comment by mmcky** [comment]
- [ ] remove `make test-all`
- [ ] adjust `make test` to run the same command as `travis` for executing local test runs.
