### ISSUE TITLE
[Tests] Build fails with Numba 0.49.0

### ISSUE THREAD

**Issue by QBatista** [QuantEcon/QuantEcon.py#530]
See https://travis-ci.org/github/QuantEcon/QuantEcon.py/jobs/676806846

There are several issues:
- `numba.targets.linalg` was moved to `numba.np.linalg` (https://github.com/numba/numba/commit/b0c408c6bbae36aa5692b1daf23e9d78162cd01e)
-  Tests for `nelder_mead` fail. This appears to be a bug with Numba because making changes in the following fashion at several places: 
```python
x_r = x_bar + ρ * (x_bar - vertices[worst_val_idx])
```
to 

```python
temp = ρ * (x_bar - vertices[worst_val_idx])
x_r = x_bar + temp
```
fixes the problem.
- Tests for `quad` fail. This appears to be related to the issue above because making the two following changes solves the issue:
```python
pp = n * (z * p1 - p2)/(z * z - 1.0)
```
to
```python
bottom = (z ** 2 - 1 )
pp = n * (z * p1 - p2) / bottom
```
 and 
```python
weights[i] = 2 * xl / ((1 - z * z) * pp * pp)
```
to 
```python
weights[i] = 2 * xl / ((1 - z ** 2) * pp ** 2)
```

**Comment by oyamad** [comment]
@QBatista Thanks for your report.

I made a fix for the first problem #531.
For the second and third:
* Will you push your fixes to the `numba049` branch to add to #531?
* Will you try to cook up a minimal working reproduce that reproduces the bug of Numba 0.49.0 as you discovered and then report it at the Numba issue tracker?

**Comment by QBatista** [comment]
@oyamad Thanks for this fix! Sure, I'll prepare the two fixes and try to cook up a minimal working example.

**Comment by QBatista** [comment]
@oyamad I've opened an issue on the Numba issue tracker: https://github.com/numba/numba/issues/5599. For the other two fixes, it seems that I don't have permission to push directly to the `numba049` branch.

**Comment by oyamad** [comment]
@QBatista Great work!

Will you push your fixes to your (or my) fork of QuantEcon.py? Then I will cherry-pick them into this PR. Thanks.

**Comment by QBatista** [comment]
@oyamad Sure -- I've pushed them to my fork here: https://github.com/QBatista/QuantEcon.py/commits/numba049.

**Comment by oyamad** [comment]
Thanks, they have been incorporated in the PR.

**Comment by stuartarchibald** [comment]
Thanks for reporting these problems on the Numba issue tracker, much appreciated.
