### ISSUE TITLE
Migrate testing to Github Actions

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#535]
Github Actions supports testing for `linux`, `os x` and `windows`. Given many of our users are on the `windows` platform -- it would be good to add testing for `windows` on each PR. Migrating to `github actions` will allow this.

**Comment by albop** [comment]
It's a good idea and I'm curious about the right way to proceed. I suppose
it would also be possible to automatically make releases on PyPi and
Conda-forge ?

**Comment by mmcky** [comment]
@Harveyt47 as part of the writeup for `contribute-python` page perhaps you can also try and setup `Github Actions` on QuantEcon.py via a PR. You can reference the [travis.yml](https://github.com/QuantEcon/QuantEcon.py/blob/master/.travis.yml) file for our current configuration and then setup `.github/workflows`. 

Please use [Github Actions docs](https://help.github.com/en/actions) and look at `.github/worfklows` in other QuantEcon software projects such as [jupyter-book](https://github.com/executablebooks/jupyter-book/tree/master/.github/workflows) -- and then ping me on slack if you get stuck.

**Comment by oyamad** [comment]
About testing (but not about Github Actions): `nose` seems left unmaintained for some time. For example, `scipy` has switched to `pytest`. Would there be enough benefits for us to switch to `pytest` net of (possibly not small) costs?

**Comment by mmcky** [comment]
hey @oyamad I think this would be a great exercise for an RA. I might ask @Harveyt47 to look into this as a project while setting up `Github Actions`. I think `pytest` is the new standard and probably worth switching over to.

**Comment by Harveyt47** [comment]
No worries @mmcky I'll look into `pytest` using `GitHub Actions`. Also how many versions of `python` do we want the tests to run on? `GitHub Actions` allows for many

**Comment by mmcky** [comment]
@Harveyt47 how are you going with this? Let me know if you have any questions etc. Or if you want to setup a PR for comments / discussion etc.

**Comment by Harveyt47** [comment]
Hi @mmcky I should I make a PR for actions with the change to `pytest`. Or should I first add the action with nose tests.

**Comment by rht** [comment]
This issue can be closed?

**Comment by mmcky** [comment]
thanks @rht
