### ISSUE TITLE
[test_quadsum.py ] undefined name

### ISSUE THREAD

**Issue by Harveyt47** [QuantEcon/QuantEcon.py#538]
I have been running tests and got the following 
```

./quantecon/tests/test_quadsum.py:60:5: F821 undefined name 'test_simplesum'
10
    test_simplesum()
11
    ^
12
./quantecon/tests/test_quadsum.py:61:5: F821 undefined name 'test_identitysum'
13
    test_identitysum()
14
    ^
15
./quantecon/tests/test_quadsum.py:63:5: F821 undefined name 'test_m_identitysum'
16
    test_m_identitysum
```
In [test_quadsum.py](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/tests/test_quadsum.py) `test_var_simplesum()` and `test_var_identitysum()` are defined but `test_simplesum` and `test_identitysum` are called.
@mmcky I got this while playing around with GitHub actions on my fork.

**Comment by oyamad** [comment]
Run

```
nosetests test_quadsum.py
```

instead of

```
python test_quadsum.py
```

But those calls should be corrected. Pull request welcome!

**Comment by mmcky** [comment]
Speaking with @Harveyt47 I think this is now resolved. Thanks @oyamad
