### ISSUE TITLE
Convert test suite from nosetests to pytest 

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#539]
It would be good to migrate our test suite from `nosetests` to `pytest`

https://docs.pytest.org/en/latest/

@Harveyt47 do you have time to look into this?

**Comment by Harveyt47** [comment]
Yep will do @mmcky .

**Comment by Harveyt47** [comment]
`pytest` has support for `nosetests` see [here](https://docs.pytest.org/en/latest/nose.html). For example this [test](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/markov/tests/test_approximation.py#L12) will work as is.

However when there is not support we will have to change functions like `setUp` to `setup_method` see [here](https://docs.pytest.org/en/latest/xunit_setup.html?highlight=setup#method-and-function-level-setup-teardown). For example the `setUp` function [here](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/markov/tests/test_core.py#L179) needs to be changed to `setup_method`

**Comment by Harveyt47** [comment]
yield tests were removed in pytest 4.0, see [here](https://docs.pytest.org/en/latest/deprecations.html#yield-tests) for needed switch

**Comment by oyamad** [comment]
@mmcky What is the status of this issue? It seems `nose` will no longer work on Python 3.10 (nose-devs/nose#1099).

**Comment by mmcky** [comment]
thanks @oyamad sounds like this can no longer sit on the back burner. 

I'll need to reserve some time to make the migration.

**Comment by mmcky** [comment]
@oyamad we have a new RA coming on board this month (hopefully) -- I might ask him to help me with this task (cc: @jstac)

**Comment by Smit-create** [comment]
Should I work on this?

**Comment by oyamad** [comment]
@Smit-create Thanks, that would be great.

I converted one file in the `game_theory` module in #597. The resulting tests work with both `nose` and `pytest`.

**Comment by oyamad** [comment]
Regarding PR #610 (thanks @Smit-create!), I didn't realize the `PytestCollectionWarning`s: [`yield tests were removed in pytest 4.0 - test_XXX will be ignored`](https://github.com/QuantEcon/QuantEcon.py/runs/5546271326#step:7:44). We need to find a substitution for `yield` in test code.

**Comment by Smit-create** [comment]
Yeah, will have a look into it.

**Comment by Smit-create** [comment]
I found the fix for that using the following:
```py
test_classes = [
    StationaryDistSumOne,
    StationaryDistNonnegative,
]

@pytest.mark.parametrize("test_class", test_classes)
def test_stoch_matrix(test_class):
    """Test with stochastic matrices"""
    matrices = Matrices()
    for matrix_dict in matrices.stoch_matrix_dicts:
        x = gth_solve(matrix_dict['A'])
        test_class()(x)
```
The only issue with this approach is that it will fail with `nosetests`. So, once we completely deprecate `nosetests`, we can use the above snippets for such tests.

**Comment by oyamad** [comment]
Convert from `nose` to `pytest` also on [`conda_ci.yml`](https://github.com/QuantEcon/QuantEcon.py/blob/496fdeaa22460824bba2ce58a7fb908e3f2216b7/.github/workflows/conda_ci.yml#L50).

**Comment by oyamad** [comment]
And fix `yield` tests in `test_gth_solve.py` and `test_ricatti.py`.

**Comment by oyamad** [comment]
Done, thanks to @Smit-create!
