### ISSUE TITLE
a_small_typo_in_quantecon.inequality.rank_size_plot

### ISSUE THREAD

**Issue by shlff** [QuantEcon/QuantEcon.py#543]
Hi @jstac and @mmcky , I notice a small possible typo in the source file of a function ``quantecon.inequality.rank_size_plot`` in the library ``QuantEcon``, please see [here](https://quanteconpy.readthedocs.io/en/latest/_modules/quantecon/inequality.html#rank_size_plot):
- ``c%`` in the sentence ``extract top c%`` should be ``(c x 100)%``.

**Comment by jstac** [comment]
Thanks @shlff, that's true.  Please put in a PR.

**Comment by shlff** [comment]
Morning @jstac . I find my commit is denied when I push it to this repo. I guess it is because I do not have permission.

If convenient, could you please grant me the access to this repo? :)

**Comment by mmcky** [comment]
@shlff done.

**Comment by shlff** [comment]
Thanks @mmcky and @jstac .
