### ISSUE TITLE
publish newer version (quantecon 0.4.7) on conda-forge?

### ISSUE THREAD

**Issue by weikang9009** [QuantEcon/QuantEcon.py#546]
Hello, our python package on space-time analysis [giddy](https://github.com/pysal/giddy) has your amazing package as a dependency. I noticed that [a newer version 0.4.7 was released last month on pypi](https://pypi.org/project/quantecon/#history), but [the newest version on condo-forge is still 0.4.5](https://anaconda.org/conda-forge/quantecon). I wonder if you have plans to release the newest version on condo-forge since [our travis testing suite is mainly relying on conda-forge](https://github.com/pysal/giddy/pull/138). Thanks!

**Comment by mmcky** [comment]
hi @weikang9009 thanks for letting us know you use the `conda-forge` channel. I have had a lot of trouble with `conda-forge` automated update PRs which took a long time to figure out so I had stopped releasing via `conda-forge`. But given the interest in supporting this channel -- I will try and setup the conda-forge feedstock again to get that back up and running. 

Just as a side note for the short term -- you can add `pip` requirements to conda `environments.yml` if that is how you specify your environment. 

```yml
...
- pip:
  - quantecon
```

here is [an example](https://github.com/QuantEcon/lecture-python/blob/2e053c1ecc0c53ed8feb7bbee852813e785d01db/environment.yml#L21)

**Comment by weikang9009** [comment]
Thanks for the quick response and great advice! 

Could you please let me know once the newer version is released on conda-forge?

**Comment by mmcky** [comment]
hi @weikang9009 thanks to wonderful `conda-forge` community support `quantecon=0.4.7` is now available via `conda-forge`

https://anaconda.org/conda-forge/quantecon

**Comment by weikang9009** [comment]
Awesome! Thanks a lot!
