### ISSUE TITLE
Numba 0.49.0: No module named 'numba.targets.linalg'

### ISSUE THREAD

**Issue by akshayshanker** [QuantEcon/QuantEcon.py#549]
Hi. 

I updated to numba 0.49.0. 

Quantecon now does not import.  I am in Python 3.7.4

Full error:
```
/home/141/as3442/.local/lib/python3.7/site-packages/numba/np/ufunc/parallel.py:355: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 10002. The TBB threading layer is disabled.
  warnings.warn(problem)
/home/141/as3442/.local/lib/python3.7/site-packages/quantecon/util/numba.py:7: NumbaDeprecationWarning: No direct replacement for 'numba.targets' available. Visit https://gitter.im/numba/numba-dev to request help. Thanks!
  from numba.targets.linalg import _LAPACK
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-37373f23d642> in <module>
----> 1 import quantecon

~/.local/lib/python3.7/site-packages/quantecon/__init__.py in <module>
     13 #-Modules-#
     14 from . import distributions
---> 15 from . import game_theory
     16 from . import quad
     17 from . import random

~/.local/lib/python3.7/site-packages/quantecon/game_theory/__init__.py in <module>
     10 )
     11 from .pure_nash import pure_nash_brute, pure_nash_brute_gen
---> 12 from .support_enumeration import support_enumeration, support_enumeration_gen
     13 from .lemke_howson import lemke_howson
     14 from .mclennan_tourky import mclennan_tourky

~/.local/lib/python3.7/site-packages/quantecon/game_theory/support_enumeration.py in <module>
     12 import numpy as np
     13 from numba import jit
---> 14 from ..util.numba import _numba_linalg_solve
     15 from ..util.combinatorics import next_k_array
     16 

~/.local/lib/python3.7/site-packages/quantecon/util/numba.py in <module>
      5 import numpy as np
      6 from numba import jit, generated_jit, types
----> 7 from numba.targets.linalg import _LAPACK
      8 
      9 

ModuleNotFoundError: No module named 'numba.targets.linalg'
```

**Comment by oyamad** [comment]
What is the version of `quantecon` you are using? The latest version is 0.4.7. You could check it by

```
pip show quantecon
```

**Comment by GabrielPestana81** [comment]
Have the same problem here. The package is correctly updated.

**Comment by mmcky** [comment]
@akshayshanker emailed me this issue on Monday and we resolved it through an upgrade to `quantecon=0.4.7` using

```
pip install quantecon --upgrade
```

@GabrielPestana81 can you confirm what version you are running using

```bash
pip show quantecon
````

It should be `Version: 0.4.7`

**Comment by mmcky** [comment]
`travis` is testing against `numba-0.49.1` so @GabrielPestana81 please let me know if an upgrade doesn't fix your issue.

**Comment by mmcky** [comment]
@GabrielPestana81 are you using `conda`? 

When I do a conda search of the `quantecon` package I actually find that `0.4.5` is available through `pkgs/main` so you may need to specify the channel `-c conda-forge` to fetch the latest version which is `0.4.7`

```bash
conda install quantecon -c conda-forge
```

or 

```bash
conda update quantecon -c conda-forge
```

**Comment by akshayshanker** [comment]
Hi. Sorry for delay. 

I updated as @oyamad  suggested. In particular, I used:

```
pip install --user 'quantecon==0.4.7'
```

The package imports and everything seems to be fine so far. However, i do get error message:
```
In [1]: import quantecon                                                                                                                                                            
/home/141/as3442/.local/lib/python3.7/site-packages/numba/np/ufunc/parallel.py:355: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 10002. The TBB threading layer is disabled.
  warnings.warn(problem)

```
Thanks for the package btw,  qe functions are staples.

**Comment by oyamad** [comment]
@akshayshanker I think it's from `numba`. Try

```py
import numba
```

on a fresh session to see if you still have the same warning.

What OS are you using?

**Comment by akshayshanker** [comment]
Hi @oyamad. 

import numba works fine without error. I cannot tell what the material relevance of the latest error message is. 

My OS is
```
NAME="CentOS Linux"
VERSION="8 (Core)"
```
version 
```
4.18.0-147.5.1.el8.nci.x86_64
```

Note I am on an HPC cluster. (https://nci.org.au/our-systems/hpc-systems)

**Comment by GabrielPestana81** [comment]
Thanks for the reply. 
Thanks @mmcky, the code for the update worked. It is a surprise though, since my version was 0.4.7. I guess you may have done some adjust in the main code. All working fine now !

  `pip install quantecon --upgrade`

**Comment by oyamad** [comment]
@akshayshanker I don't know what "TBB" is, but this part https://github.com/numba/numba/blob/23a5c659e1122c607deb291ff5f7dd796f2a2915/numba/np/ufunc/parallel.py#L329-L360 in `numba` is checking whether "the TBB version is new enough". You could call that function by

```py
numba.np.ufunc.parallel._check_tbb_version_compatible()
```

(One of my computers is running on an old version of Mac OS X, where I see that same warning, whereas I haven't had any problem with that.)

**Comment by oyamad** [comment]
Maybe related: https://numba.discourse.group/t/suppress-tbb-warning/

**Comment by oyamad** [comment]
Closing.
