### ISSUE TITLE
Compatibility with Python=3.9

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#559]
It looks like we may have some compatibility issues with `python=3.9`

https://github.com/conda-forge/quantecon-feedstock/pull/23#issuecomment-739217657

**Comment by oyamad** [comment]
Maybe due to numba/numba#6345?

**Comment by oyamad** [comment]
Just to report, all the tests pass with Python `3.9.1` and Numba `0.53.0rc1`.

See https://numba.discourse.group/t/numba-0-53-0-and-llvmlite-0-36-0-release-candidates to install Numba `0.53.0rc1`.

**Comment by mmcky** [comment]
thanks @oyamad this is really helpful.

**Comment by oyamad** [comment]
It turned out I was testing against Python 3.8...
With PR #573 tests pass with `python=3.9.1`, `numba=0.53.0rc2`, and `llvmlite=0.36.0rc2`.
