### ISSUE TITLE
Python 3: The models/jv.py optimization

### ISSUE THREAD

**Issue by cc7768** [QuantEcon/QuantEcon.py#56]
Currently the jv.py file is having issues calling the scipy.optimize minimization routine SLSQP in python 3.  Currently, we call the SLSQP in python 2.7 and COBYLA for python 3.  Unforunately, the COBYLA routine creates convergence problems for compute_fixed_point and never comes within 1e-2 in either python 2 or python 3 (I terminated it at ~250 iterations when it was oscillating between 0.03 and 0.011).  This causes the test test_jv.py to fail because we expect a higher degree of accuracy.  We need to figure out why the call to SLSQP isn't working in python 3 even though it works in python 2.

Here is some example code.
```
import numpy as np
from quantecon.models.jv import JvWorker
from quantecon.compute_fp import compute_fixed_point


jv = JvWorker()
sze = jv.x_grid.size

v_init = jv.x_grid * .65
sol = compute_fixed_point(jv.bellman_operator, v_init,
                          max_iter=3000,
                          error_tol=1e-5)

jv.bellman_operator(sol)
```

**Comment by mmcky** [comment]
@cc7768 This code is no longer contained in the QuantEcon package. Can I close this issue?
