### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by rht** [QuantEcon/QuantEcon.py#571]
See https://github.com/github/renaming. The web renaming tool was made ready just 3 days ago as of this commit: https://github.com/github/renaming/commit/040636ea50e945875c70cc964d586f645e9bd810.

**Comment by mmcky** [comment]
Thanks for this link @rht 

I have reserved some time next week to do some maintenance on this package. I will see if we can migrate this then.
