### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [QuantEcon/QuantEcon.py#583]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine quantecon/markov/tests/test_ddp.py and observe `approxmation`, however expect to see `approximation`.
- Examine quantecon/game_theory/tests/test_vertex_enumeration.py and observe `reponse`, however expect to see `response`.
- Examine quantecon/estspec.py and observe `frequences`, however expect to see `frequencies`.
- Examine docs/sphinxext/ipython_console_highlighting.py and observe `typicaly`, however expect to see `typically`.
- Examine quantecon/compute_fp.py and observe `theorm`, however expect to see `theorem`.
- Examine quantecon/lqcontrol.py and observe `symetric`, however expect to see `symmetric`.
- Examine quantecon/game_theory/vertex_enumeration.py and observe `reprensenting`, however expect to see `representing`.
- Examine quantecon/tests/test_ivp.py and observe `parameteric`, however expect to see `parametric`.
- Examine docs/sphinxext/ipython_directive.py and observe `orignal`, however expect to see `original`.
- Examine quantecon/game_theory/pure_nash.py and observe `equilibirum`, however expect to see `equilibrium`.
- Examine quantecon/util/notebooks.py and observe `defualt`, however expect to see `default`.
- Examine quantecon/filter.py and observe `arrray`, however expect to see `array`.
- Examine quantecon/lss.py and observe `convariance`, however expect to see `covariance`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/QuantEcon.py/pull/new/bugfix_typos

Thanks.

**Comment by oyamad** [comment]
@timgates42 PR would be appreciated!

**Comment by timgates42** [comment]
Thanks @oyamad have added one
