### ISSUE TITLE
M1 Mac Install

### ISSUE THREAD

**Issue by milind** [QuantEcon/QuantEcon.py#587]
I am currently running a late 2020 MacBook Air with an M1 chip and I was unable to install using conda / pip through any of the suggested channels. Curious if anyone else had any luck installing the package on an M1 Mac and what your process was to get it to work. (For the time being, I'll probably just use it in a Google Colab Notebook but would love to transition over to running it on my own machine). Please let me know if you need any more information and I'm happy to provide it.

**Comment by jstac** [comment]
Thanks for the report @milind .

Could you please copy and paste your error message?  

@mmcky should be able to assist after he sees the messages.

**Comment by mmcky** [comment]
thanks @milind for reporting this issue. 

Any error output would be greatly apprecited to help in diagnosing the issue.

QuantEcon.py is a source distribution so should work if you have python setup and installed. 
Do you have python / anaconda installed and up and running?

**Comment by milind** [comment]
Hi @jstac and @mmcky - Thanks so much for the fast reply! I tried running `conda install -c conda-forge quantecon`. I'm currently running the native terminal (without Rosetta on) and an arm build of miniforge. Listed below is the error output that I got from that command. Thanks!

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - quantecon

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by mmcky** [comment]
Ah that is super helpful. Thanks @milind. I suspect we may need to add the `osx-arm64` builds to our `conda forge` recipe.

Do you get any error if you use `pip`?

```
pip install quantecon --upgrade
```

**Comment by mmcky** [comment]
@milind will try to fix this in `conda-forge` but if I run into trouble I may need to ping the `conda-forge` team on this

https://github.com/conda-forge/quantecon-feedstock/pull/26

**Comment by mmcky** [comment]
@milind it hasn't been just a simple config fix unfortunately. 
I will need to spend a bit of time to figure out how to get `osx-arm64` supported via `conda-forge` build machinery.

Thanks again for reporting this. I may need to look at this next week (shuffling a few priorities).

**Comment by mmcky** [comment]
I would be interested in the `pip` output if you get the chance to test it. Thanks.

**Comment by milind** [comment]
I appreciate you looking into it! - with regard to the pip install, I've tried it for several packages before on this laptop but each time the install comes across a dependency that it is unable to resolve, going down the version list until it escapes out of the sequence. There is a massive list of error messages but this is the last one for llvmlite. I believe that scipy, numba, and llvmlite are the packages that ran into issues here, which is why I tend to use conda as my default package manager instead.

```
ERROR: Command errored out with exit status 1: [filepath for conda] -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c1/06y4bhv92bv93g70gkhdj8nc0000gn/T/pip-install-s8nx9hqy/llvmlite_cf4e1a33173b4023ad536b4e57ae4a24/setup.py'"'"'; __file__='"'"'/private/var/folders/c1/06y4bhv92bv93g70gkhdj8nc0000gn/T/pip-install-s8nx9hqy/llvmlite_cf4e1a33173b4023ad536b4e57ae4a24/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c1/06y4bhv92bv93g70gkhdj8nc0000gn/T/pip-record-m6b1g8bt/install-record.txt --single-version-externally-managed --compile --install-headers [filepath for conda] Check the logs for full command output.
```

Happy to test anything else out or send a different part of this error message if it would be helpful. Thanks again :)

**Comment by mmcky** [comment]
@milind thanks for the info. Looks like `llvm_lite` may not have an `ox-arm64` build? I will try to look into that -- as that will be crucial infrastructure for `QuantEcon.py` to run.

**Comment by mmcky** [comment]
@milind this looks like it is currently an open issue 

https://github.com/numba/llvmlite/issues/665

It is encouraging that there is a PR waiting for review to try and fix this issue. I think this will need to be resolved before we can role out `QuantEcon.py` on `arm64` architecture.

**Comment by milind** [comment]
@mmcky Got it! I appreciate you looking into this and look forward to getting to test out the arm builds whenever the dependencies get around to sorting things out. Thanks!

**Comment by jstac** [comment]
Thanks for letting us know @milind .  All feedback is appreciated.  Hopefully that PR gets merged soon.

**Comment by mmcky** [comment]
thanks @milind I have now asked `conda-forge` team to add us to the `arm64` builds and we have now merged 

https://github.com/conda-forge/quantecon-feedstock/pull/28

I don't have an M1 mac so it would be great if you could let me know if this get's added and is working for you. 

Thanks for your patience while we figured this out.

**Comment by mmcky** [comment]
@milind the `conda-forge` page is now showing the `arm64` badge 🎉 

https://anaconda.org/conda-forge/quantecon

**Comment by milind** [comment]
@mmcky Just tested it out and it works like a charm! 🎉 Thanks so much for the work that you've put into this project and looking forward to getting into the weeds of it soon!

**Comment by mmcky** [comment]
great - thanks for the feedback @milind.

I will likely get access to an  `m1` in January but in the meantime let me know if you run into any issues. Cheers.
