### ISSUE TITLE
`nosetests` does not work on windows CI job

### ISSUE THREAD

**Issue by Smit-create** [QuantEcon/QuantEcon.py#603]
We have the Github Actions job that runs on all three platforms for testing `quantecon`. `nosetests` seems to be working fine on Linux and mac, but not on windows. See https://github.com/QuantEcon/QuantEcon.py/runs/5148553158?check_suite_focus=true. It logs saying:
`Ran 0 tests in 5.394s`

I tried to figure out the problem but seems to be a platform-dependent issue from `nosetests`? Probably the best fix is to start moving towards `pytest`. One related answer on [StackOverflow](https://stackoverflow.com/questions/59288817/nosetests-not-recognized-on-windows) also suggests the same.

**Comment by mmcky** [comment]
Agreed @Smit-create -- I think moving towards pytest is the right answer here :-)
