### ISSUE TITLE
CI failing on Master Branch

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#607]
It looks like `Conda` tests are failing on the `master` branch. 

This will need to be fixed before any other PR's are merged 

cc @Smit-create

**Comment by Smit-create** [comment]
The tests seems to be failing because of precision error. Might be the issue when we test using random numbers (without seed). We just need to raise the error limit to fix it. I will have a look at it soon.

**Comment by oyamad** [comment]
Also `TestTicTacToc.test_loop` in `util/tests/test_timing.py` is [failing](https://github.com/QuantEcon/QuantEcon.py/runs/5747742400#step:6:66) on `windows-latest, 3.8`.

**Comment by Smit-create** [comment]
> Also `TestTicTacToc.test_loop` in `util/tests/test_timing.py` is [failing](https://github.com/QuantEcon/QuantEcon.py/runs/5747742400#step:6:66) on `windows-latest, 3.8`.

I guess that is a random failure. We can slightly raise the time bar if there are frequent failures due to this.

**Comment by mmcky** [comment]
Closing this now -- given #620
