### ISSUE TITLE
Python3.4 Compatibility Issues ... Package Support

### ISSUE THREAD

**Issue by sanguineturtle** [QuantEcon/QuantEcon.py#61]
Issue with 1 x nosetest failure in python3.4:

The issue is that the anaconda installer for python3.4 doesn't package statsmodels or scikits. There are 141 packages in python 3.4 version of anaconda vs. 197 packages in the python 2.7 version. 

Also running ``conda install statsmodels`` renders an “Unsatisfiable package specifications” error. 

http://stackoverflow.com/questions/23343484/python-3-statsmodels

It does look like the majority of statsmodels will however run in python 3.
http://statsmodels.sourceforge.net/devel/introduction.html#python-3

It also looks like statsmodels is available in the continuum repository of packages for py3.3 – but there must be some conflict with python3.4. [If it’s in python 3.3 I can’t imagine it will be long] I have emailed continuum to see if there is a timeline for inclusion. Then perhaps we can compile a list of dependencies and check them against 3.4 standard inclusions.

In the meantime - should we put a warning box on page http://quant-econ.net/getting_started.html that the majority of the package will work with python 3.4 but from time to time a few errors may crop up due to the evolving package support in python3.4?

**Comment by spencerlyon2** [comment]
Ping. @mmcky, have you tried testing against 3.4 with new anaconda?

**Comment by mmcky** [comment]
@spencerlyon2 Just ran tests in a new python 3 environment. Most are passing! :+1: 
``244 tests in 81.099s (SKIP=2)``

Python2.4 environment runs ``247 tests in 80.49s (SKIP=1)``

I will have to dig a bit further to see why there are 3 different tests under Python2.4. Any ideas of the top of your head?

**Comment by cc7768** [comment]
Look at `test_jv.py`.  I think we skipped them because something wasn't working right.  I don't remember exactly what, I think it had to do with the optimization.

**Comment by mmcky** [comment]
I see Travis is also passing for Python 3.3. 

@jstac Propose to close this item. Should we remove the suggestion in the lecture notes to use Python 2.7 or wait a little longer until we test it out a bit more under Python 3? I would probably suggest wait a little longer until we start using python3 in development etc. as some of the packages we use (such as ``fabric``) is still python 2.7. 

Also for Anaconda. Python2.7 still has 244 packages to Python 3.4 which was 171. But python 3 support is growing quickly.

**Comment by jstac** [comment]
@mmcky I'll let you take care of this.  Please close or leave open as you and others see fit. Let's leave the suggestion in the lectures for a bit longer.

**Comment by mmcky** [comment]
Travis is currently passing. Main issues dealt with in this issue. Closing.
