### ISSUE TITLE
Add code for VAR approximation

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#639]
Replicate Matlab routines from ``Finite-State Approximation Of  VAR Processes:  A Simulation Approach'' by Stephanie Schmitt-Grohé and Martín Uribe, July 11, 2010. 

The Matlab code is in the zip file [Discrete_VAR.zip](https://github.com/QuantEcon/QuantEcon.py/files/9712903/Discrete_VAR.zip)

In that same zip file is Python code that replicates the results of the Matlab routine, provided by @crondonm.  Next stages are

1. create a PR
2. shift code to PEP8
3. try to make code more numerically efficient
4. add tests

I've asked @crondonm to submit a PR.

**Comment by oyamad** [comment]
Done by #640!
