### ISSUE TITLE
Fix Quantecon documentation site

### ISSUE THREAD

**Issue by Smit-create** [QuantEcon/QuantEcon.py#644]
See: https://quanteconpy.readthedocs.io/en/latest/optimize/linprog_simplex.html

The function arguments are not displayed properly

<img width="1440" alt="Screenshot 2022-10-28 at 7 24 49 PM" src="https://user-images.githubusercontent.com/55887635/198626710-c6e934b6-c81a-4780-9841-6f030a79e978.png">

**Comment by oyamad** [comment]
There are similar reports in readthedocs/sphinx_rtd_theme#766 and other issues as linked from there (but I haven't read those long discussions...).

**Comment by Smit-create** [comment]
This work around works for me:
```diff
diff --git a/docs/source/conf.py b/docs/source/conf.py
index ca37505..431173e 100644
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -86,6 +86,8 @@ extensions = [
     'matplotlib.sphinxext.plot_directive',
 ]
 
+html4_writer = True
+
 # Add any paths that contain templates here, relative to this directory.
 templates_path = ['_templates']

```

![image](https://user-images.githubusercontent.com/55887635/200172629-c2e0961f-bb3e-40c9-95f1-e842e4a374ee.png)

**Comment by oyamad** [comment]
#651 does not seem to have fixed this issue: see for example https://quanteconpy.readthedocs.io/en/latest/tools/filter.html.

**Comment by oyamad** [comment]
This is no longer an issue.
