### ISSUE TITLE
TEST: Raise atol in test for `optimize.nelder_mead`

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.py#662]
`test_rotated_hyper_ellipsoid` fails occasionally:
https://github.com/QuantEcon/QuantEcon.py/actions/runs/3583327063/jobs/6028627522#step:8:73
https://github.com/QuantEcon/QuantEcon.py/actions/runs/3588801874/jobs/6040576063#step:8:73

Maybe loosen `atol=1e-7` to `atol=1e-6`?

**Comment by QBatista** [comment]
This could be due to the fact that the initial guess is drawn randomly, so it might work better to set a seed for the initial guess.

**Comment by oyamad** [comment]
Hi @QBatista thanks, but test failure implies that there are instances such that the computed result differs from the analytical outcome by more than the current `atol`. If it is the feature of the implementation, I think the tolerance should be adjusted accordingly.

**Comment by QBatista** [comment]
@oyamad That's a fair point, but is the convergence of the algorithm theoretically guaranteed in this example? We know analytically what the maximum of the function is but I'm not sure if we know whether the algorithm should converge to it.

**Comment by oyamad** [comment]
That I don't know. A test case should be an instance for which convergence is known.
Or, a practical strategy is just to increase `atol` to say `1e-6` and see if the test fails sometime (with randomly drawn initial guesses as in the current code).
