### ISSUE TITLE
Migrate Commit History?

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#671]
When cleaning up the `API` the commit history is not longer super clear from #601 

For example `arma.py` was migrated to `_arma.py` (with `arma.py` retained to preserve backward compatibility). 

Can the commit history of `arma.py` be concatenated to `_arma.py`?

**Comment by Smit-create** [comment]
I tried to save the commit history to the new file using `git mv`. I see that the reason it got lost is due to merge conflicts and when I resolved those conflicts manually, it somehow got messed up. I will try to look into this.

**Comment by Smit-create** [comment]
One option is that we can revert that PR and then I'll come up with a new PR fixing that in one go such that we don't have any merge conflicts.

**Comment by Smit-create** [comment]
I checked by merging #674 into a copy of `main` branch in my fork and found that the commit history is not overridden, i.e., it uses the same old commits: https://github.com/Smit-create/QuantEcon.py/tree/check_671_merge

Another solution that I found is this:
1. Revert PR #601 and merge it in the `main`.
2. Merge #674 into the `main` and you can see the results as expected. This is how it would look: https://github.com/Smit-create/QuantEcon.py/commits/check_671_5/quantecon/_arma.py

**Comment by oyamad** [comment]
Resolved by #682
