### ISSUE TITLE
Add function fit_discrete_mc

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#678]
As discussed in https://github.com/QuantEcon/QuantEcon.py/pull/640, we should add a function called `fit_discrete_mc` that takes  a time series $X_0, \ldots, X_{T-1}$ taking values in $\mathbb R^n$ (each $X_t$ is a vector in continuous state space $\mathbb R^n$) and fits a finite Markov chain to it using the following steps:

1. Set up a one-dimensional grid in each dimension of $\mathbb R^n$ (e.g., if $n=2$ then set up a grid on the $x$ axis and the $y$ axis)
2. Take the cartesian product of these 1D grids to get a set of grid points in $\mathbb R^n$
3. Produce a new time series $\hat X_0, \ldots, \hat X_{T-1}$ by mapping each $X_t$ to the nearest grid point in $\mathbb R^n$.
4. Fit a finite Markov chain to the new time series and return as a `MarkovChain` object.

This function just combines existing tools, since

#. for step 3, we can use `cartesian_nearest_index`
#. for step 4, we can use `estimate_mc` (see https://github.com/QuantEcon/QuantEcon.py/pull/658)

@oyamad Could you please confirm that you agree?
@Smit-create @HumphreyYang might you be willing to collaborate on this issue?

**Comment by oyamad** [comment]
One thing I am concerned with is that it is less general than what the general name `fit_discrete_mc` would suggest, in that the state space of the finite MC will be just a Cartesian product. I would like to have an implementation that would warrant future extendability. Suppose that the function will be called with `fit_discrete_mc(X, S)`.

* For now, as `S` it accepts an array_like (typically tuple) of array_like's of 1D grid points.
* In a future extension, add a `cartesian` option (with default `True`), where with `cartesian=False`, `S` will be a 2D array_like of n-dimensional points (which will be the state space of `mc`).

If this works, we can proceed for now as you propose.

**Comment by jstac** [comment]
Thanks for your comments @oyamad .

The extension you suggest sounds like a good idea.  My understanding is that someone can proceed now in line with my suggestion and your bullet point one. We can then open as issue to add the enhancement that you suggested.

**Comment by Smit-create** [comment]
Thanks @jstac and @oyamad ,
So are we trying to implement something like this?
```py
def fit_discrete_mc(X, S):
    X_new = cartesian_nearest_index(X, S)
    return estimate_mc(X_new)
```

**Comment by jstac** [comment]
Hi @Smit-create , yes, that's all we need.  The same lines appear in https://github.com/QuantEcon/QuantEcon.py/commit/745c0d447a95277aadbbc66c50a6dc9656bafe36.  

Notice that there's also an `order` keyword argument, which determines whether the cartesian product is counted in row major or column major.  The default should be `'C'`, which is row major.

Many thanks!

**Comment by oyamad** [comment]
See this part: https://github.com/QuantEcon/QuantEcon.py/blob/745c0d447a95277aadbbc66c50a6dc9656bafe36/quantecon/markov/approximation.py#L367-L375

**Comment by oyamad** [comment]
Done by #681
