### ISSUE TITLE
License mismatch between repo and JOSS paper

### ISSUE THREAD

**Issue by janosg** [QuantEcon/QuantEcon.py#711]
In your [joss draft](https://github.com/openjournals/joss-papers/blob/joss.05585/joss.05585/10.21105.joss.05585.pdf) (line 46) you say that QuantEcon.py is released under a MIT license. However, the [LICENSE file](https://github.com/QuantEcon/QuantEcon.py/blob/main/LICENSE)  is BSD-3. 

openjournals/joss-reviews#5585

**Comment by mmcky** [comment]
Thanks @janosg

The following PR https://github.com/QuantEcon/QuantEcon.py/pull/712 will address this, just seeking approval from all lead developers and then it will be merged.

**Comment by mmcky** [comment]
fixed by #712
