### ISSUE TITLE
conda releases stalled

### ISSUE THREAD

**Issue by knaaptime** [QuantEcon/QuantEcon.py#720]
hey folks, just wanted to call https://github.com/conda-forge/quantecon-feedstock to attention in case there's no notification (i easily miss the conda-forge stuff myself).

I think the feedstock just needs the last PR merged (and maybe the automerge-bot added?)
but there might be a few small dependency tweaks for the latest version. Happy to help out if you want to add me as a recipe maintainer. :)

**Comment by mmcky** [comment]
thanks @knaaptime -- really helpful.

I will look into this.

**Comment by knaaptime** [comment]
sure, let me know if there's anything i can do. This is causing a few [breakages for us downstream](https://github.com/pysal/giddy/issues/208) where we depend on qe because the newer numba versions dropped the compatibility layer (obviously the fix has already been merged and released here, conda just cant pull the updates)

**Comment by knaaptime** [comment]
resolved :) I'll keep an eye on it, but [grayskull](https://github.com/conda/grayskull) should hande everything on the conda side from now on
