### ISSUE TITLE
Fix numba deprecation notice

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#721]
The following https://intro.quantecon.org/inequality.html#measurement shows a `numba` deprecation warning from the `quantecon` package

**Comment by oyamad** [comment]
I believe it is coming from `interpolation`.
See #701.

**Comment by jstac** [comment]
@mmcky , I suggest replacing `interp` from `interpolation` with the function of the same name from NumPy.

**Comment by oyamad** [comment]
This is an issue of `interpolation` (and has been fixed by EconForge/interpolation.py#114).
