### ISSUE TITLE
ENH: Add basic interpolation routine

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#722]
Add basic `jit` enabled interpolation routine to `quantecon` and leave more complex interpolation to the `interpolations` package.

**Comment by mmcky** [comment]
```python
@jit
def interp(grid, vals, x):
    """
    Linearly interpolate (grid, vals) to evaluate at x.
    Here grid must be regular (evenly spaced).

    Parameters
    ----------
    grid and vals are numpy arrays, x is a float

    Returns
    -------
    a float, the interpolated value
    """

    a, b, len_g = np.min(grid), np.max(grid), len(grid)
    s = (x - a) / (b - a)
    q_0 = max(min(int(s * (len_g - 1)), (len_g - 2)), 0)
    v_0 = vals[q_0]
    v_1 = vals[q_0 + 1]
    λ = s * (len_g - 1) - q_0
    return (1 - λ) * v_0 + λ * v_1
```

**Comment by jstac** [comment]
Thanks @mmcky .  It would be really helpful for me if this was added and released soon.

At the same time, it might be best if we change it everwhere so that the order of the positional arguments matches https://numpy.org/doc/stable/reference/generated/numpy.interp.html

That means searching through all lectures to find every place where it's called.

In terms of adding tests, the function should match the output of numpy.interp

**Comment by mmcky** [comment]
thanks @jstac.  

Will prioritise this.

**Comment by mmcky** [comment]
> Thanks @mmcky . It would be really helpful for me if this was added and released soon.
> 
> At the same time, it might be best if we change it everwhere so that the order of the positional arguments matches https://numpy.org/doc/stable/reference/generated/numpy.interp.html
> 
> That means searching through all lectures to find every place where it's called.
> 
> In terms of adding tests, the function should match the output of numpy.interp

@jstac looking at the `numpy` docs it seems the function splits the x and y coordinates

https://numpy.org/doc/stable/reference/generated/numpy.interp.html

Are you proposing we change from

```
def interp(grid, vals, x):
```

to 

```
def interp(x, grid, vals):
```

and `grid` is equivalent to numpy `xp` and vals are `fp`. Is that correct?

**Comment by jstac** [comment]
That's right @mmcky .

We might even change `grid` to `xp` and `vals` to `fp` throughout.

**Comment by mmcky** [comment]
@jstac 

```
q_0 = max(min(int(s * (len_g - 1)), (len_g - 2)), 0)
```

would you like this function to broadcast over an array of `x` values? 

`numba` doesn't know how to cast `int` over an array.

**Comment by jstac** [comment]
Ah, good catch.  It might be better if it broadcasts --- and also returns a float if called on a float.

However, if that's too much hassle and the calling code in the lectures only calls on floats I'm fine without broadcasting.

**Comment by mmcky** [comment]
Closing this as using `np.interp`
