### ISSUE TITLE
Quantecon not installing on Mac M2

### ISSUE THREAD

**Issue by thunder-bom** [QuantEcon/QuantEcon.py#732]
running 

conda install quantecon 

in terminal gives

Channels:
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: / warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package quantecon-0.5.0-py310hca03da5_0 requires python >=3.10,<3.11.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.12.* , which can be installed;
└─ quantecon is not installable because there are no viable options
   ├─ quantecon [0.5.0|0.7.0] would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   ├─ quantecon [0.5.0|0.7.0] would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   ├─ quantecon [0.5.0|0.7.0] would require
   │  └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
   └─ quantecon 0.7.0 would require
      └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported.

However, quantecon can be installed via pip.  What is going on?  I would like to use conda, so that updates etc are easier to track.  

Any thoughts?

**Comment by oyamad** [comment]
`conda install quantecon` seems to install an older version (`v0.5.0`).

Running
```py
conda install conda-forge::quantecon
```
instead seems to work, installing `v0.7.2` (see https://anaconda.org/conda-forge/quantecon).

I don't know what is happening, @mmcky?

**Comment by thunder-bom** [comment]
Yes, running` conda install conda-forge::quantecon` does work.  And I can also now update using

`conda upgrade quantecon`

Thanks for your help

**Comment by mmcky** [comment]
> `conda install quantecon` seems to install an older version (`v0.5.0`).
> 
> Running
> 
> ```python
> conda install conda-forge::quantecon
> ```
> 
> instead seems to work, installing `v0.7.2` (see https://anaconda.org/conda-forge/quantecon).
> 
> I don't know what is happening, @mmcky?

The `quantecon` package is available in the default conda channel -- which is great but it sometimes lags the condo-forge releases.
