### ISSUE TITLE
Improve PyPi quantecon page

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#85]
Some basic information needs to be added to this page:

https://pypi.python.org/pypi/quantecon

As a model, see, for example, this page:

https://pypi.python.org/pypi/gunicorn/

**Comment by spencerlyon2** [comment]
ping

Do we have a better pypi page/readme yet?

**Comment by jstac** [comment]
It could definitely be improved.  @mmcky Did we have a plan for this?  I don't want to replicate info from quantecon.org but it might be good to make the page look a bit nicer and have the link to quantecon.org more prominent.

**Comment by mmcky** [comment]
@jstac Put together some suggestions which can be found in the PR just submitted. 
I have followed the lead of ``pandas`` and integrated the PYPI information into ``setup.py`` - which will flow through to PYPI without a manual upload.

**Comment by mmcky** [comment]
This should propagate through to the PYPI page when we next update PyPI.
