### ISSUE TITLE
Broken links in docstrings / readthedocs, slightly urgent

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#91]
A lot of links in the docstrings, and hence readthedocs, have been broken by the code reorganization.  For example, the link

http://quant-econ.net/kalman.html

in 

http://quanteconpy.readthedocs.org/en/latest/tools/kalman.html

**Comment by spencerlyon2** [comment]
I noticed we took most of these links out of the source files.

Now that urls have settled down, do we want to add them back in?

**Comment by jstac** [comment]
Right, I forgot about this.  It would be great to have the links fixed.  Many are still broken.  Eg.,

https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/kalman.py

The links could go in the docstrings or in the display attributes for print, etc.

**Comment by mmcky** [comment]
Just went through grep and fixed the links without ``py`` and ones that have had names changes. Do we need to add other reference links as per @spencerlyon2 comment?

**Comment by jstac** [comment]
@mmcky Could you please clarify?  It sounds like you've already dealt with the issues mentioned by @spencerlyon2

**Comment by mmcky** [comment]
@jstac I have fixed a few links that are currently contained within the docstrings by checking all grep matches of ``html://`` and reviewing them. I read @spencerlyon2's comment to suggest that in the past some of the reference links were deleted from the docstrings and that some may need to be reinstated?
