### ISSUE TITLE
Accessing the cartesian routine

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.py#98]
Hi,
I wanted to use [`cartesian`](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/cartesian.py), but found it a bit tricky to access it.

Does not work:
```python
import quantecon as qe
qe.cartesian([[0, 1], [0, 1], [0, 1]])
```
It raises `AttributeError: 'module' object has no attribute 'cartesian'`.
(The same goes for `qe.cartesian.cartesian([[0, 1], [0, 1], [0, 1]])`.)

Works:
```python
import quantecon.cartesian
quantecon.cartesian.cartesian([[0, 1], [0, 1], [0, 1]])
```

Is this as intended?
It is not mentioned in the [documentation](https://quanteconpy.readthedocs.org/en/latest/tools/cartesian.html).

**Comment by spencerlyon2** [comment]
Seems like this is resolved. Can anyone confirm and close?

**Comment by albop** [comment]
The cartesian package has to be renamed to `gridtools` or `grid_tools` as @jstac has suggested. Both seem perfect to me.

**Comment by spencerlyon2** [comment]
I'd vote for `gridtools`.

**Comment by jstac** [comment]
Fine by me.
